/* ── CPAG pack as slides ──
   The pack is read as a deck, by slide position, so the screen presents it as
   one — same running order as the .pptx, same slide for the same content.

   Slides that no connected system can fill are still issued, in place, stating
   what is missing. Dropping them would make the pack look shorter than it is,
   when the reporting gap is the finding.

   Each slide is a fixed 16:9 board scaled to fit, so a slide looks the same at
   any window size and matches what downloads. */
import React, { useState, useEffect, useMemo, useRef, useCallback } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import {
  X, ChevronLeft, ChevronRight, Maximize2, Minimize2, Download,
  List, Info,
} from 'lucide-react';
import ReactECharts from 'echarts-for-react';
import { cx } from '../../components/ui/primitives';
import { useChartTheme } from '../../lib/chartTheme';

/* ── Formatting ── */
const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
                'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

export const MONTH_LABEL = (m: string) => {
  const [y, mm] = m.split('-');
  return `${MONTHS[Number(mm) - 1]}-${y.slice(2)}`;
};
export const DATE = (s: string | null | undefined) =>
  s ? new Date(s).toLocaleDateString('en-GB',
    { day: '2-digit', month: 'short', year: '2-digit' }) : '—';
export const NUM = (n: number | null | undefined, dp = 0) =>
  n === null || n === undefined ? '—'
    : n.toLocaleString('en-IN', { minimumFractionDigits: dp, maximumFractionDigits: dp });
export const PCT = (n: number | null | undefined, dp = 1) =>
  n === null || n === undefined ? '—' : `${n.toFixed(dp)}%`;

/* echarts-for-react measures once at mount and then listens only to window
   resizes. The slide stage rescales without the window changing, so the
   container is observed directly. */
export const Chart = ({ option, height }: { option: any; height: number }) => {
  const ref = useRef<any>(null);
  const box = useRef<HTMLDivElement>(null);
  const { themeName } = useChartTheme();
  useEffect(() => {
    if (!box.current) return;
    const ro = new ResizeObserver(() => ref.current?.getEchartsInstance()?.resize());
    ro.observe(box.current);
    return () => ro.disconnect();
  }, []);
  return (
    <div ref={box} className="w-full" style={{ height }}>
      <ReactECharts ref={ref} option={option} theme={themeName} notMerge lazyUpdate
        style={{ height: '100%', width: '100%' }} />
    </div>
  );
};

/* The board is authored at a fixed size and scaled, so type and spacing keep
   their proportions instead of reflowing into a different design per window. */
const BOARD_W = 1280;
const BOARD_H = 720;

export interface Slide {
  id: string;
  section: string;
  title: string;
  subtitle?: string;
  render: () => React.ReactNode;
}

/* ── Slide furniture ──
   Drawn with the template's own artwork, lifted out of the pack and served
   from /cpag: the header bar and footer mark from its master, the cover
   illustration and the section-divider lockup from its layouts. The board is
   the standard, so the screen uses the standard rather than an approximation. */
const ART = '/akasha/cpag';

const Board: React.FC<{
  title: string; subtitle?: string; index: number; total: number;
  children: React.ReactNode; footnote?: string;
}> = ({ title, subtitle, index, total, children, footnote }) => (
  <div className="relative flex flex-col bg-white"
    style={{ width: BOARD_W, height: BOARD_H }}>
    {/* Master furniture: accent bar over a full-width hairline */}
    <div className="shrink-0 px-[62px] pt-[34px]">
      <img src={`${ART}/master-a.png`} alt="" aria-hidden
        className="block h-[5px] w-[59%] object-fill" />
      <div className="mt-[3px] h-px w-full bg-[#d9dde3]" />
      <h2 className="mt-[10px] text-[23px] font-bold leading-tight tracking-tight text-[#1a1a1a]">
        {title}
      </h2>
      {subtitle && (
        <p className="mt-0.5 text-[13px] font-medium text-[#6b7280]">{subtitle}</p>
      )}
    </div>

    <div className="min-h-0 flex-1 px-[62px] pt-2">{children}</div>

    <div className="shrink-0 px-[62px] pb-[18px]">
      {footnote && (
        <p className="mb-1.5 text-[10.5px] italic leading-snug text-[#6b7280]">{footnote}</p>
      )}
      <div className="flex items-center justify-between border-t border-[#d9dde3] pt-1.5">
        <span className="text-[10px] font-medium uppercase tracking-[0.1em] text-[#9aa1ab]">
          Adani Green Energy · CPAG review · generated by Akasha from P6, SAP and Pulse
        </span>
        <span className="flex items-center gap-2.5">
          <span className="text-[11px] font-semibold text-[#6b7280]">{index} / {total}</span>
          <img src={`${ART}/logo.png`} alt="" aria-hidden className="h-[18px] w-auto" />
        </span>
      </div>
    </div>
  </div>
);

/* Cover: the pack's illustration full-bleed. Its sky is the only area with
   room for type, so the title sits top-left over it in dark ink. */
const CoverBoard: React.FC<{ title: string; subtitle: string; stamp: string }> = ({
  title, subtitle, stamp,
}) => (
  <div className="relative overflow-hidden bg-[#d9eef7]"
    style={{ width: BOARD_W, height: BOARD_H }}>
    <img src={`${ART}/cover-photo.jpg`} alt="" aria-hidden
      className="absolute inset-x-0 bottom-0 w-full object-cover object-bottom"
      style={{ height: '88%' }} />
    <div className="absolute left-[62px] top-[58px] max-w-[62%]">
      <p className="text-[12px] font-bold uppercase tracking-[0.2em] text-[#0b74b1]">
        CPAG review pack
      </p>
      <h1 className="mt-3 text-[46px] font-black leading-[1.08] tracking-tight text-[#12263f]">
        {title}
      </h1>
      <p className="mt-3 text-[18px] font-semibold text-[#2b4f6e]">{subtitle}</p>
      <div className="mt-5 h-[3px] w-28 bg-[#0b74b1]" />
      <p className="mt-3 text-[13px] text-[#3d5a73]">{stamp}</p>
    </div>
  </div>
);

/* Section divider: the template's grey field, wordmark and orange band, with
   the heading reversed out of the band exactly where the layout puts it. */
const SectionBoard: React.FC<{ title: string }> = ({ title }) => (
  <div className="relative overflow-hidden bg-[#f0f0f2]"
    style={{ width: BOARD_W, height: BOARD_H }}>
    <img src={`${ART}/section-a.png`} alt="" aria-hidden
      className="absolute inset-0 h-full w-full object-cover" />
    <div className="absolute inset-x-0 flex items-center px-[80px]"
      style={{ top: '57.5%', height: '19%' }}>
      <h1 className="text-[38px] font-bold leading-tight text-white drop-shadow-sm">
        {title}
      </h1>
    </div>
  </div>
);

/* A slide the systems cannot fill. It still ships — titled, in position, and
   explicit about what is missing. */
const UnavailableBoard: React.FC<{ reason: string; needs?: string }> = ({ reason, needs }) => (
  <div className="flex h-full items-center justify-center">
    <div className="max-w-[660px] rounded-xl border border-[#e0e3e8] bg-[#f6f7f9] px-10 py-9 text-center">
      <p className="text-[11px] font-bold uppercase tracking-[0.14em] text-[#9aa1ab]">
        Not available from connected systems
      </p>
      <p className="mt-4 text-[16px] leading-relaxed text-[#1a1a1a]">{reason}</p>
      {needs && (
        <p className="mt-4 text-[13px] italic leading-relaxed text-[#6b7280]">{needs}</p>
      )}
    </div>
  </div>
);

/* ── Table, styled as the deck prints it ──
   `groups` draws the pack's upper header row: each entry spans `span` columns,
   and a group with no label leaves the column to the row beneath, which then
   spans both rows. */
interface Group { label: string; span: number }

/* Verified against the circulated deck's own table fills (slide XML dump,
   2026-09-24): 7030A0 is the header purple used most often across the deck
   (176 of 312 header cells sampled), and body rows are plain white almost
   everywhere - there is no alternating row band in the native tables. The
   one exception is Procurement, which tints by COLUMN (grey over ordering
   columns, peach over delivery-tracking columns) - reproduced via `colTint`. */
const HEADER_PURPLE = '#7030A0';
const GREY_COL = '#F2F2F2';
const PEACH_COL = '#FBE2D5';

const T: React.FC<{
  head: string[]; rows: (string | React.ReactNode)[][];
  groups?: Group[];
  widths?: number[]; size?: number; align?: ('l' | 'r')[];
  compact?: boolean;
  colTint?: ('grey' | 'peach' | null)[];
}> = ({ head, rows, groups, widths, size = 13, align, compact, colTint }) => {
  const headCell = cx('border border-[#5a2680] font-semibold text-white',
    compact ? 'px-2 py-1' : 'px-2.5 py-1.5');
  const tintColor = (t: 'grey' | 'peach' | null | undefined) =>
    t === 'grey' ? GREY_COL : t === 'peach' ? PEACH_COL : '#ffffff';
  /* A column covered by a labelled group is headed twice, so its lower cell is
     drawn; a column under an unlabelled group spans both rows instead. */
  const spannedTwice: boolean[] = [];
  if (groups) {
    groups.forEach((g) => {
      for (let i = 0; i < g.span; i += 1) spannedTwice.push(Boolean(g.label));
    });
  }
  return (
    <table className="w-full table-fixed border-collapse" style={{ fontSize: size }}>
      {widths && (
        <colgroup>{widths.map((w, i) => <col key={i} style={{ width: `${w}%` }} />)}</colgroup>
      )}
      <thead>
        {groups && (
          <tr>
            {groups.map((g, i) => {
              const firstCol = groups.slice(0, i).reduce((a, x) => a + x.span, 0);
              return g.label ? (
                <th key={i} colSpan={g.span} style={{ background: HEADER_PURPLE }}
                  className={cx(headCell, 'text-center')}>
                  {g.label}
                </th>
              ) : (
                <th key={i} colSpan={g.span} rowSpan={2} style={{ background: HEADER_PURPLE }}
                  className={cx(headCell, align?.[firstCol] === 'r' ? 'text-right' : 'text-left')}>
                  {head[firstCol]}
                </th>
              );
            })}
          </tr>
        )}
        <tr>
          {head.map((h, i) => (
            (groups && !spannedTwice[i]) ? null : (
              <th key={i} style={{ background: HEADER_PURPLE }}
                className={cx(headCell, align?.[i] === 'r' ? 'text-right' : 'text-left')}>
                {h}
              </th>
            )
          ))}
        </tr>
      </thead>
      <tbody>
        {rows.map((r, ri) => (
          <tr key={ri}>
            {r.map((c, ci) => (
              <td key={ci}
                style={{ background: tintColor(colTint?.[ci]) }}
                className={cx('border border-[#c9ccd2] text-[#1a1a1a]',
                  compact ? 'px-2 py-[2.5px]' : 'px-2.5 py-[6px]',
                  align?.[ci] === 'r' ? 'text-right tabular-nums' : 'text-left')}>
                {c}
              </td>
            ))}
          </tr>
        ))}
      </tbody>
    </table>
  );
};

const varColor = (v: number | null | undefined) =>
  v === null || v === undefined ? '#101828'
    : v <= -25 ? '#d92d20' : v <= -10 ? '#f79009' : '#12b76a';

/* ── Slide builders ── */
interface BuildArgs {
  projects: any[];
  meta: any;
  commercial: any;
  manpower: any;
  financial?: any;
  single: boolean;
}

export function buildSlides({ projects, meta, commercial, manpower, financial, single }: BuildArgs): Slide[] {
  const out: Slide[] = [];
  const label = projects.map((p) => p.pss).join(', ');
  const half = Math.max(1, Math.ceil(projects.length / 2));
  const groups = [projects.slice(0, half), projects.slice(half)].filter((g) => g.length);
  const add = (s: Slide) => out.push(s);

  const unavailable = (section: string, title: string, subtitle: string,
                       reason: string, needs?: string) =>
    add({ id: `${title}-${subtitle}`, section, title, subtitle,
          render: () => <UnavailableBoard reason={reason} needs={needs} /> });

  /* A single-project pack is named for that project; the portfolio pack for
     the programme. Either way the cover says what it is and how current. */
  const coverTitle = single
    ? `${projects[0].pss} — CPAG Report`
    : 'Battery Energy Storage Systems — CPAG Report';
  const coverSub = single
    ? `${projects[0].spv} · Plot ${projects[0].plot ?? '—'} · ${NUM(projects[0].powerMw)} MW / ${NUM(projects[0].energyMwh)} MWh`
    : `${meta.projectCount ?? projects.length} projects · ${NUM(meta.powerMw)} MW / ${NUM(meta.energyMwh)} MWh · FY 2026-27`;
  add({
    id: 'cover', section: 'Cover', title: coverTitle,
    render: () => (
      <CoverBoard
        title={coverTitle}
        subtitle={coverSub}
        stamp={`Khavda RE Park, Gujarat · reported to ${meta.lastActualMonth ? MONTH_LABEL(meta.lastActualMonth) : '—'} · generated by Akasha from P6, SAP and Pulse`}
      />
    ),
  });

  add({
    id: 'capacity', section: 'Overview', title: 'Battery Energy Storage Systems',
    subtitle: 'Projects : FY 2026-27',
    render: () => (
      <div className="flex h-full items-start justify-center pt-6">
        <div className="w-[70%]">
          <T
            head={['PSS', 'Power', 'Energy', 'Dispatchable Energy', 'Containers']}
            align={['l', 'r', 'r', 'r', 'r']}
            size={15}
            rows={[
              ...projects.map((p) => [p.pss, `${NUM(p.powerMw)} MW`,
                `${NUM(p.energyMwh)} MWh`, `${NUM(p.dispatchableMwh)} MWh`,
                NUM(p.containers)]),
              [<strong key="t">Total</strong>,
               <strong key="p">{NUM(meta.powerMw)} MW</strong>,
               <strong key="e">{NUM(meta.energyMwh)} MWh</strong>,
               <strong key="d">{NUM(meta.dispatchableMwh)} MWh</strong>,
               <strong key="c">{NUM(meta.containers)}</strong>],
            ]}
          />
        </div>
      </div>
    ),
  });

  add({
    id: 'salient', section: 'Overview', title: 'Salient Features', subtitle: label,
    render: () => (
      <div className="space-y-5">
        <T
          head={['PSS', 'SPV', 'Plot', 'Battery OEM', 'Containers', 'Land (acres)',
                 'Approvals', 'Ordered ₹Cr']}
          align={['l', 'l', 'l', 'l', 'r', 'r', 'r', 'r']}
          rows={projects.map((p) => [p.pss, p.spv, p.plot ?? '—', p.batteryOem,
            NUM(p.containers), NUM(p.landAcres, 2),
            `${p.approvalsDone}/${p.approvalsTotal}`,
            p.sapAvailable ? NUM(p.orderCr, 1) : 'civil only'])}
        />
        <div className="grid grid-cols-3 gap-4 text-[14px]">
          {[['Project capacity', `${NUM(meta.powerMw)} MW / ${NUM(meta.energyMwh)} MWh`],
            ['Location', 'Khavda RE Park, Gujarat'],
            ['Order book', `₹${NUM(commercial.orderCr, 1)} Cr · ${NUM(commercial.poCount)} POs`]]
            .map(([k, v]) => (
              <div key={k} className="rounded-lg border border-[#e4e7ec] bg-[#f7f8fa] px-4 py-3">
                <p className="text-[11px] font-semibold uppercase tracking-wide text-[#98a2b3]">{k}</p>
                <p className="mt-1 font-semibold text-[#101828]">{v}</p>
              </div>
            ))}
        </div>
      </div>
    ),
  });

  unavailable('Overview', 'Overall Layout', label,
    'Plot geometry for the BESS parcels is not held in any connected system.',
    'Would need the Khavda park layout drawing with plot boundaries.');

  if (projects.some((p) => p.commissioning?.items?.length))
    add(commissioningSlide(projects, label));
  else
    unavailable('Overview', 'Commissioning Plan', label,
      'The month-by-month MWh and container commissioning plan has no system of record.',
      'P6 carries commissioning activities and dates, but not the MWh or container quantity released in each month.');

  projects.forEach((p) => add(sCurveSlide(p)));

  if (projects.some((p) => p.engineering?.total))
    add(engineeringSlide(projects, label));
  else
    unavailable('Overview', 'Engineering Progress', label,
      'The engineering master document log — total documents, cumulative received and approvals by category — is not ingested.',
      'Would need the Phase-II master log from SharePoint.');

  add(sectionSlide(`Procurement Status: ${label}`));
  projects.forEach((p) => add(procurementSlide(p)));

  groups.forEach((g) => {
    add(sectionSlide(`${g.map((p: any) => p.pss).join(', ')} Progress`));
    g.forEach((p: any) => {
      if (p.construction?.elements?.length) add(civilSlide(p));
      else unavailable('Construction', `Civil Construction Progress (Plan vs Actual) (${p.pss})`, p.spv,
        'Element-level civil progress is measured on installed physical quantity, tracked in site spreadsheets.',
        'P6 Material resources hold these quantities under the Construction branches.');
      if (p.electrical?.items?.length) add(electricalSlide(p));
      else unavailable('Construction', `Electrical Plan vs Actual Summary (${p.pss})`, p.spv,
        'Element-level electrical progress is reported on running metres laid and units erected.',
        'P6 Material resources hold these quantities under the Construction branches.');
    });
  });

  add(sectionSlide(`Manpower & Mandays Status: ${label}`));
  add(mandaysSlide(manpower, label));
  add(manpowerCurveSlide(manpower, label));
  projects.forEach((p) => {
    if (p.contractors?.length) add(contractorSlide(p));
    else unavailable('Manpower', `Contractor Manpower Status (${p.pss})`, p.spv,
      'Contractor headcount by month — forecast, actual and shortfall — is not held in any connected system.',
      'Contractor identity exists in SAP and Pulse; the deployed and required headcount does not.');
  });

  if (projects.some((p) => p.quality?.rfiTotal)) add(qualitySlide(projects, label));

  unavailable('Review', 'Major Milestones — Next 3 Months', label,
    'The forward milestone commitments, with delivery quantities per month, are compiled manually for the review.',
    'P6 holds the milestone dates; the container and PCS quantities promised per month have no source.');
  unavailable('Review', 'Critical Issues FY 26-27', label,
    'The issue register — impact, corrective action, owner and support required — is narrative and has no system of record.',
    'Variance and slip are measured throughout this pack; the commentary around them is not.');

  add(financialSlide(financial ?? { series: [] }, label));

  groups.forEach((g) => {
    const gl = g.map((p: any) => p.pss).join(', ');
    add(sectionSlide(`Ordering Status ${gl}`));
    (['Supply', 'Service'] as const).forEach((kind) => {
      const rows = buildOrderingRows(g, kind);
      const pageCount = Math.max(1, Math.ceil(rows.length / ORDERING_PAGE_SIZE));
      for (let pg = 0; pg < pageCount; pg += 1) {
        const chunk = rows.slice(pg * ORDERING_PAGE_SIZE, (pg + 1) * ORDERING_PAGE_SIZE);
        add(orderingSlide(chunk, pg * ORDERING_PAGE_SIZE, rows.length, kind, gl,
          `page ${pg + 1} of ${pageCount}`));
      }
    });
  });

  groups.forEach((g) => {
    add(sectionSlide(`Statutory & Other approvals ${g.map((p: any) => p.pss).join(', ')}`));
    g.forEach((p: any) => {
      const items = p.approvals ?? [];
      const mid = Math.ceil(items.length / 2);
      add(approvalsSlide(p, 0, mid, 'page 1 of 2'));
      add(approvalsSlide(p, mid, items.length, 'page 2 of 2'));
    });
  });

  if (!single) {
    ['PSS-10A', 'PSS-05A', 'PSS-08A'].forEach((legacy) =>
      unavailable('Phase-1', `Physical Progress : ${legacy} S-Curve`, 'Phase-1 BESS',
        `No P6 schedule exists for ${legacy} in the connected systems.`,
        'Pulse holds inspection records for this unit, but without a schedule there is no plan or actual to curve.'));
  }

  add({
    id: 'thanks', section: 'Close', title: 'Thank You',
    render: () => <SectionBoard title="Thank You" />,
  });

  return out;
}

/* Engineering — the pack prints a document master log we do not ingest, so
   this reports the engineering *activities* P6 does hold and says so. */
const engineeringSlide = (projects: any[], label: string): Slide => ({
  id: 'engineering', section: 'Engineering',
  title: 'Engineering Progress', subtitle: label,
  render: () => <EngineeringBody projects={projects} />,
});

const EngineeringBody: React.FC<{ projects: any[] }> = ({ projects }) => {
  const { categorical, chrome } = useChartTheme();

  /* Monthly release across the whole scope, so the chart reads as the pack's
     does rather than as six small ones. */
  const months = useMemo(() => {
    const set = new Set<string>();
    projects.forEach((p) => (p.engineering?.monthly ?? [])
      .forEach((m: any) => set.add(m.month)));
    return [...set].sort();
  }, [projects]);

  const series = useMemo(() => {
    const plan: number[] = [], act: number[] = [];
    let cp = 0, ca = 0;
    const planCum: number[] = [], actCum: number[] = [];
    months.forEach((m) => {
      let pm = 0, am = 0;
      projects.forEach((p) => {
        const row = (p.engineering?.monthly ?? []).find((x: any) => x.month === m);
        pm += row?.planMonth ?? 0;
        am += row?.actualMonth ?? 0;
      });
      plan.push(pm); act.push(am);
      cp += pm; ca += am;
      planCum.push(cp); actCum.push(ca);
    });
    return { plan, act, planCum, actCum };
  }, [months, projects]);

  const option = useMemo(() => ({
    grid: { left: 44, right: 44, top: 30, bottom: 26, containLabel: true },
    tooltip: { trigger: 'axis' },
    legend: { show: true, top: 0, right: 0, itemWidth: 14, itemHeight: 8, itemGap: 14 },
    xAxis: { type: 'category', data: months.map(MONTH_LABEL) },
    yAxis: [
      { type: 'value', name: 'Cumulative' },
      { type: 'value', name: 'Monthly', splitLine: { show: false }, minInterval: 1 },
    ],
    series: [
      { name: 'Plan (month)', type: 'bar', yAxisIndex: 1, barWidth: '30%',
        data: series.plan,
        itemStyle: { color: chrome.gridLine, borderRadius: [2, 2, 0, 0] } },
      { name: 'Actual (month)', type: 'bar', yAxisIndex: 1, barWidth: '30%',
        data: series.act,
        itemStyle: { color: categorical[1], borderRadius: [2, 2, 0, 0] } },
      { name: 'Plan cumulative', type: 'line', symbol: 'none', smooth: 0.2,
        data: series.planCum,
        lineStyle: { width: 2, type: 'dashed', color: chrome.fgTertiary },
        itemStyle: { color: chrome.fgTertiary } },
      { name: 'Actual cumulative', type: 'line', symbol: 'none', smooth: 0.2,
        data: series.actCum,
        lineStyle: { width: 2.5, color: categorical[0] },
        itemStyle: { color: categorical[0] },
        areaStyle: { opacity: 0.08, color: categorical[0] } },
    ],
  }), [months, series, categorical, chrome]);

  const cell = (p: any, name: string) => {
    const g = (p.engineering?.groups ?? []).find((x: any) => x.name === name);
    return g ? `${g.completed}/${g.total}` : '—';
  };
  const basis = projects.find((p) => p.engineering?.basis)?.engineering?.basis;

  return (
    <div className="flex h-full flex-col gap-3">
      <div className="grid min-h-0 flex-1 grid-cols-[1.25fr_1fr] gap-6">
        <div className="min-w-0"><Chart option={option} height={352} /></div>
        <T head={['PSS', 'Basic', 'Detailed', 'Tech. spec.', 'Total', 'Done', '%']}
          align={['l', 'r', 'r', 'r', 'r', 'r', 'r']} size={12}
          widths={[20, 13, 14, 15, 13, 12, 13]}
          rows={projects.map((p) => {
            const e = p.engineering ?? {};
            return [p.pss, cell(p, 'Basic Engineering'),
              cell(p, 'Detailed Engineering'), cell(p, 'Technical Sepcification'),
              NUM(e.total), NUM(e.completed),
              PCT(e.total ? (e.completed / e.total) * 100 : null, 0)];
          })} />
      </div>
      <p className="shrink-0 text-[11px] italic leading-snug text-[#6b7280]">{basis}</p>
    </div>
  );
};

/* Commissioning — the pack schedules MWh and containers per month; P6 holds
   the phase milestones and their dates, so those are reported instead. */
const commissioningSlide = (projects: any[], label: string): Slide => ({
  id: 'commissioning', section: 'Commissioning',
  title: 'Commissioning Plan', subtitle: label,
  render: () => <CommissioningBody projects={projects} />,
});

const CommissioningBody: React.FC<{ projects: any[] }> = ({ projects }) => {
  const { categorical } = useChartTheme();

  const months = useMemo(() => {
    const set = new Set<string>();
    projects.forEach((p) => (p.commissioning?.monthly ?? [])
      .forEach((m: any) => set.add(m.month)));
    return [...set].sort();
  }, [projects]);

  const option = useMemo(() => ({
    grid: { left: 44, right: 20, top: 30, bottom: 26, containLabel: true },
    tooltip: { trigger: 'axis' },
    legend: { show: projects.length > 1, top: 0, right: 0, itemWidth: 12, itemHeight: 8 },
    xAxis: { type: 'category', data: months.map(MONTH_LABEL) },
    yAxis: { type: 'value', name: 'Milestones', minInterval: 1 },
    series: projects.map((p, i) => ({
      name: p.pss, type: 'bar', stack: 'total',
      data: months.map((m) => {
        const row = (p.commissioning?.monthly ?? []).find((x: any) => x.month === m);
        return row?.milestones ?? 0;
      }),
      itemStyle: { color: categorical[i % categorical.length] },
    })),
  }), [months, projects, categorical]);

  const basis = projects.find((p) => p.commissioning?.basis)?.commissioning?.basis;

  return (
    <div className="flex h-full flex-col gap-3">
      <div className="grid min-h-0 flex-1 grid-cols-[1fr_1fr] gap-5">
        <div className="min-w-0"><Chart option={option} height={330} /></div>
        <T head={['PSS', ...months.map(MONTH_LABEL), 'Total']}
          align={['l', ...months.map(() => 'r' as const), 'r']} size={12}
          rows={projects.map((p) => {
            const by = new Map((p.commissioning?.monthly ?? [])
              .map((m: any) => [m.month, m.milestones]));
            const vals = months.map((m) => (by.get(m) as number) ?? 0);
            return [p.pss, ...vals.map((v) => (v ? String(v) : '—')),
              <strong key="t">{vals.reduce((a, b) => a + b, 0)}</strong>];
          })} />
      </div>
      <p className="shrink-0 text-[11px] italic leading-snug text-[#6b7280]">
        {basis} Counts are commissioning and trial-run milestones falling in each month,
        not MWh released.
      </p>
    </div>
  );
};

/* Quality — not in the circulated pack, but it is measured, it is per project,
   and it is the nearest evidence for the construction variance the pack
   reports, so it earns a slide. */
const qualitySlide = (projects: any[], label: string): Slide => ({
  id: 'quality', section: 'Quality', title: 'Quality Record',
  subtitle: `Inspection requests and non-conformances from Pulse · ${label}`,
  render: () => <QualityBody projects={projects} />,
});

const QualityBody: React.FC<{ projects: any[] }> = ({ projects }) => {
  const { categorical, status } = useChartTheme();

  const option = useMemo(() => ({
    grid: { left: 44, right: 20, top: 30, bottom: 26, containLabel: true },
    tooltip: { trigger: 'axis' },
    legend: { show: true, top: 0, right: 0, itemWidth: 14, itemHeight: 8 },
    xAxis: { type: 'category', data: projects.map((p) => p.pss) },
    yAxis: { type: 'value', name: 'Records' },
    series: [
      { name: 'Inspections raised', type: 'bar', barWidth: '34%',
        data: projects.map((p) => p.quality?.rfiTotal ?? 0),
        itemStyle: { color: categorical[0], borderRadius: [3, 3, 0, 0] } },
      { name: 'Non-conformances', type: 'bar', barWidth: '34%',
        data: projects.map((p) => p.quality?.ncTotal ?? 0),
        itemStyle: { color: status.risk, borderRadius: [3, 3, 0, 0] } },
    ],
  }), [projects, categorical, status]);

  const pkg = (p: any, name: string) =>
    (p.quality?.rfiByPackage ?? []).find((r: any) => r.package === name)?.count ?? 0;

  return (
    <div className="flex h-full flex-col gap-3">
      <div className="grid min-h-0 flex-1 grid-cols-[1fr_1.2fr] gap-6">
        <div className="min-w-0"><Chart option={option} height={352} /></div>
        <T head={['PSS', 'Inspections', 'NCs', 'Open NCs', 'NC rate',
                  'Civil RFIs', 'Elec. RFIs']}
          align={['l', 'r', 'r', 'r', 'r', 'r', 'r']} size={12}
          widths={[16, 17, 11, 14, 14, 14, 14]}
          rows={projects.map((p) => {
            const q = p.quality ?? {};
            return [p.pss, NUM(q.rfiTotal), NUM(q.ncTotal), NUM(q.openNc),
              <span key="r" style={{ color: (q.ncRatePct ?? 0) >= 25 ? '#d92d20'
                : (q.ncRatePct ?? 0) >= 10 ? '#f79009' : '#1a1a1a', fontWeight: 600 }}>
                {PCT(q.ncRatePct, 1)}
              </span>,
              NUM(pkg(p, 'Civil')), NUM(pkg(p, 'Electrical'))];
          })} />
      </div>
      <p className="shrink-0 text-[11px] italic leading-snug text-[#6b7280]">
        Pulse records. Not a slide in the circulated pack — included because it is measured per
        project and is the nearest evidence for the construction variance reported earlier.
      </p>
    </div>
  );
};

/* The pack colours an actual bar by how much of plan it reached — green at or
   above 80%, yellow 40-80%, red below. Plan is always blue. That rule is the
   pack's own legend, so it is reproduced rather than re-invented. */
const achievementColor = (pct: number | null | undefined) => {
  if (pct === null || pct === undefined) return '#9aa1ab';
  if (pct >= 80) return '#00a650';
  if (pct >= 40) return '#ffd11a';
  return '#e8112d';
};
const PLAN_BLUE = '#2e9bd6';

const civilSlide = (p: any): Slide => ({
  id: `civil-${p.pss}`, section: 'Construction',
  title: `Civil Construction Progress (Plan vs Actual) (${p.pss})`,
  subtitle: p.spv,
  render: () => <CivilBody project={p} />,
});

const CivilBody: React.FC<{ project: any }> = ({ project }) => {
  /* Named elements are the pack's rows; the unnamed remainder is a long tail of
     one-off stages that would crowd the slide without telling anyone anything. */
  const elements = useMemo(
    () => (project.construction?.elements ?? [])
      .filter((e: any) => e.element !== 'General')
      .slice(0, 10),
    [project]);

  const option = useMemo(() => ({
    grid: { left: 40, right: 16, top: 30, bottom: 58, containLabel: true },
    tooltip: { trigger: 'axis', valueFormatter: (v: number) => `${Number(v).toFixed(1)}%` },
    legend: { show: false },
    xAxis: { type: 'category', data: elements.map((e: any) => e.element),
      axisLabel: { fontSize: 10, rotate: 0 } },
    yAxis: { type: 'value', min: 0, max: 100, interval: 20,
      axisLabel: { formatter: '{value}%', fontSize: 10 } },
    series: [
      { name: 'Plan', type: 'bar', barWidth: '30%',
        data: elements.map(() => 100),
        itemStyle: { color: PLAN_BLUE },
        label: { show: true, position: 'top', fontSize: 9, formatter: '100%' } },
      { name: 'Actual', type: 'bar', barWidth: '30%',
        data: elements.map((e: any) => ({
          value: e.pct, itemStyle: { color: achievementColor(e.pct) },
        })),
        label: { show: true, position: 'top', fontSize: 9,
          formatter: (d: any) => `${Number(d.value).toFixed(0)}%` } },
    ],
  }), [elements]);

  /* Stage columns are taken from whichever element carries the most of them,
     so the grid reads like the pack's element-by-stage table. */
  const lead = elements.reduce(
    (a: any, b: any) => ((b.stages?.length ?? 0) > (a?.stages?.length ?? 0) ? b : a),
    elements[0]);
  const stageNames: string[] = (lead?.stages ?? []).slice(0, 6).map((s: any) => s.stage);

  return (
    <div className="flex h-full flex-col gap-2.5">
      <div className="grid min-h-0 flex-1 grid-cols-[1.15fr_1fr] gap-5">
        <div className="min-w-0 overflow-hidden">
          <T
            head={['Element', 'Stages', 'Planned', 'Actual', 'Progress']}
            align={['l', 'r', 'r', 'r', 'r']} size={11}
            widths={[30, 13, 20, 20, 17]}
            rows={elements.map((e: any) => [
              e.element, String(e.stageCount), NUM(e.planned), NUM(e.actual),
              <span key="p" style={{ color: achievementColor(e.pct), fontWeight: 700 }}>
                {PCT(e.pct, 0)}
              </span>,
            ])}
          />
        </div>
        <div className="min-w-0"><Chart option={option} height={300} /></div>
      </div>

      {stageNames.length > 0 && (
        <div className="shrink-0">
          <p className="mb-1 text-[10px] font-semibold uppercase tracking-wide text-[#9aa1ab]">
            {lead.element} — stage detail
          </p>
          <T
            head={['Stage', 'Planned', 'Actual', 'Progress']}
            align={['l', 'r', 'r', 'r']} size={10.5}
            widths={[52, 16, 16, 16]}
            rows={(lead.stages ?? []).slice(0, 5).map((st: any) => [
              st.stage, NUM(st.planned), NUM(st.actual),
              <span key="p" style={{ color: achievementColor(st.pct), fontWeight: 700 }}>
                {PCT(st.pct, 0)}
              </span>,
            ])}
          />
        </div>
      )}

      <div className="flex shrink-0 items-center gap-4 text-[10px] text-[#6b7280]">
        <span className="flex items-center gap-1.5">
          <span className="inline-block h-2.5 w-4 rounded-[1px]" style={{ background: PLAN_BLUE }} />Plan
        </span>
        <span className="flex items-center gap-1.5">
          <span className="inline-block h-2.5 w-4 rounded-[1px]" style={{ background: '#00a650' }} />Actual ≥ 80%
        </span>
        <span className="flex items-center gap-1.5">
          <span className="inline-block h-2.5 w-4 rounded-[1px]" style={{ background: '#ffd11a' }} />40–80%
        </span>
        <span className="flex items-center gap-1.5">
          <span className="inline-block h-2.5 w-4 rounded-[1px]" style={{ background: '#e8112d' }} />below 40%
        </span>
        <span className="ml-auto italic">{project.construction?.basis}</span>
      </div>
    </div>
  );
};

const electricalSlide = (p: any): Slide => ({
  id: `elec-${p.pss}`, section: 'Construction',
  title: `Electrical Plan Vs Actual Summary ${p.pss}`, subtitle: p.spv,
  render: () => <ElectricalBody project={p} />,
});

const ElectricalBody: React.FC<{ project: any }> = ({ project }) => {
  const items = project.electrical?.items ?? [];
  const option = useMemo(() => ({
    grid: { left: 40, right: 14, top: 26, bottom: 96, containLabel: true },
    tooltip: { trigger: 'axis', valueFormatter: (v: number) => `${Number(v).toFixed(0)}%` },
    legend: { show: false },
    xAxis: { type: 'category', data: items.map((i: any) => i.element),
      axisLabel: { fontSize: 9, rotate: 55, interval: 0 } },
    yAxis: { type: 'value', min: 0, max: 100, interval: 20,
      axisLabel: { formatter: '{value}%', fontSize: 10 } },
    series: [
      { name: 'Plan', type: 'bar', barWidth: '32%',
        data: items.map(() => 100), itemStyle: { color: PLAN_BLUE },
        label: { show: true, position: 'top', fontSize: 8, formatter: '100%' } },
      { name: 'Actual', type: 'bar', barWidth: '32%',
        data: items.map((i: any) => ({
          value: i.actualPct, itemStyle: { color: achievementColor(i.actualPct) } })),
        label: { show: true, position: 'top', fontSize: 8,
          formatter: (d: any) => `${Number(d.value).toFixed(0)}%` } },
    ],
  }), [items]);

  return (
    <div className="flex h-full flex-col gap-2.5">
      <div className="grid min-h-0 flex-1 grid-cols-[1.05fr_1fr] gap-5">
        <div className="min-w-0">
          {/* The pack prints Scope and Plan as separate columns even though they
              hold the same figure here (Plan is phased flat across full scope,
              since P6 carries no dated quantity curve). Both are kept, rather
              than merged, so the column count matches the pack exactly. */}
          <T
            head={['Element', 'UoM', 'Scope', 'Plan', 'Actual', 'Plan %', 'Actual %']}
            align={['l', 'l', 'r', 'r', 'r', 'r', 'r']} size={10}
            widths={[28, 8, 13, 13, 13, 12, 13]}
            rows={items.map((i: any) => [
              i.element, i.uom, NUM(i.scope), NUM(i.plan ?? i.scope), NUM(i.actual), '100%',
              <span key="p" style={{ color: achievementColor(i.actualPct), fontWeight: 700 }}>
                {PCT(i.actualPct, 0)}
              </span>,
            ])}
          />
        </div>
        <div className="min-w-0"><Chart option={option} height={330} /></div>
      </div>
      <div className="flex shrink-0 items-center gap-4 text-[10px] text-[#6b7280]">
        <span className="flex items-center gap-1.5">
          <span className="inline-block h-2.5 w-4" style={{ background: PLAN_BLUE }} />Plan
        </span>
        <span className="flex items-center gap-1.5">
          <span className="inline-block h-2.5 w-4" style={{ background: '#00a650' }} />Actual ≥ 80%
        </span>
        <span className="flex items-center gap-1.5">
          <span className="inline-block h-2.5 w-4" style={{ background: '#ffd11a' }} />40–80%
        </span>
        <span className="flex items-center gap-1.5">
          <span className="inline-block h-2.5 w-4" style={{ background: '#e8112d' }} />below 40%
        </span>
        <span className="ml-auto max-w-[62%] truncate italic">{project.electrical?.basis}</span>
      </div>
    </div>
  );
};

const sectionSlide = (title: string): Slide => ({
  id: `sec-${title}`, section: 'Divider', title,
  render: () => <SectionBoard title={title} />,
});

const sCurveSlide = (p: any): Slide => ({
  id: `scurve-${p.pss}`, section: 'Physical progress',
  title: `Physical Progress : ${p.pss} S-Curve`, subtitle: p.spv,
  render: () => <SCurveBody project={p} />,
});

/* The pack states a cause beside every variance. Ours are narrative and have
   no system of record, so each row carries the measured fact nearest to it
   instead of an invented sentence. */
const bucketRemark = (b: any, p: any): string => {
  const within = b.withinBucketPct;
  switch (b.key) {
    case 'statutory': {
      const done = p.approvalsDone ?? 0, tot = p.approvalsTotal ?? 0;
      return `${done} of ${tot} approvals complete; ${tot - done} outstanding.`;
    }
    case 'engineering': {
      const e = p.engineering;
      return e?.total
        ? `${e.completed} of ${e.total} engineering activities complete.`
        : 'Engineering activities complete.';
    }
    case 'procurement': {
      const pkgs = p.packages?.length ?? 0;
      const recd = (p.packages ?? []).filter((pk: any) =>
        (pk.milestones ?? []).some((m: any) =>
          m.name.toLowerCase().includes('receipt at site') && m.actualFinish)).length;
      return `${recd} of ${pkgs} packages have receipts at site; `
        + `₹${NUM(p.deliveredCr, 1)} Cr of ₹${NUM(p.orderCr, 1)} Cr delivered.`;
    }
    default: {
      const q = p.quality;
      return `${PCT(within, 0)} of construction scope earned; `
        + `${NUM(q?.openNc)} non-conformances open against ${NUM(q?.rfiTotal)} inspections.`;
    }
  }
};

const SCurveBody: React.FC<{ project: any }> = ({ project }) => {
  const { categorical, chrome } = useChartTheme();
  const curve = project.sCurve ?? [];

  /* The pack puts monthly bars and cumulative lines on one frame, on two value
     axes — the burn and the position read together. */
  const option = useMemo(() => ({
    grid: { left: 46, right: 46, top: 26, bottom: 22, containLabel: true },
    tooltip: {
      trigger: 'axis',
      valueFormatter: (v: number) =>
        v === null || v === undefined ? 'not reported' : `${Number(v).toFixed(2)}%`,
    },
    legend: { show: true, top: 0, right: 0, itemWidth: 13, itemHeight: 8, itemGap: 12,
      textStyle: { fontSize: 10 } },
    xAxis: { type: 'category', data: curve.map((c: any) => MONTH_LABEL(c.month)),
      axisLabel: { fontSize: 10 } },
    yAxis: [
      { type: 'value', min: 0, max: 100, interval: 20,
        axisLabel: { formatter: '{value}%', fontSize: 10 } },
      { type: 'value', min: 0, max: 25, interval: 5, splitLine: { show: false },
        axisLabel: { formatter: '{value}%', fontSize: 10 } },
    ],
    series: [
      { name: 'Monthly plan', type: 'bar', yAxisIndex: 1, barWidth: '26%',
        data: curve.map((c: any) => c.planMonthPct),
        itemStyle: { color: categorical[0], borderRadius: [2, 2, 0, 0] }, z: 1 },
      { name: 'Monthly actual', type: 'bar', yAxisIndex: 1, barWidth: '26%',
        data: curve.map((c: any) => c.actualMonthPct),
        itemStyle: { color: categorical[1], borderRadius: [2, 2, 0, 0] }, z: 1 },
      { name: 'Cumulative plan', type: 'line', symbol: 'none', smooth: 0.25,
        data: curve.map((c: any) => c.planCumPct),
        lineStyle: { width: 2.2, color: categorical[0] },
        itemStyle: { color: categorical[0] }, z: 3 },
      { name: 'Cumulative actual', type: 'line', symbol: 'none', smooth: 0.25,
        connectNulls: false,
        data: curve.map((c: any) => c.actualCumPct),
        lineStyle: { width: 2.6, color: categorical[1] },
        itemStyle: { color: categorical[1] }, z: 3,
        endLabel: { show: true, fontSize: 11, fontWeight: 'bold',
          formatter: (d: any) => (d.value === null ? '' : `${Number(d.value).toFixed(2)}%`) } },
    ],
  }), [curve, categorical, chrome]);

  const plan = project.planToDatePct ?? 0;
  const actual = project.actualPct ?? 0;
  const months = curve.map((c: any) => MONTH_LABEL(c.month));

  /* The per-month grid the pack prints under the plot, so the reader can take
     a number off it without reading the chart. */
  const grid: [string, (c: any) => number | null][] = [
    ['Monthly plan', (c) => c.planMonthPct],
    ['Monthly actual', (c) => c.actualMonthPct],
    ['Cumulative plan', (c) => c.planCumPct],
    ['Cumulative actual', (c) => c.actualCumPct],
  ];

  return (
    <div className="flex h-full flex-col gap-1.5">
      <div className="shrink-0"><Chart option={option} height={175} /></div>

      <table className="w-full shrink-0 table-fixed border-collapse text-[9px]">
        <colgroup>
          <col style={{ width: '13%' }} />
          {months.map((_: string, i: number) => (
            <col key={i} style={{ width: `${87 / Math.max(months.length, 1)}%` }} />
          ))}
        </colgroup>
        <thead>
          <tr>
            <th className="border border-[#e0e3e8] bg-[#f6f7f9] px-1.5 py-0.5 text-left font-semibold text-[#6b7280]" />
            {months.map((m: string) => (
              <th key={m} className="border border-[#e0e3e8] bg-[#f6f7f9] px-0.5 py-0.5 text-center font-semibold text-[#1a1a1a]">
                {m}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {grid.map(([label, pick], ri) => (
            <tr key={label}>
              <td className="border border-[#e0e3e8] px-1.5 py-[2px] font-semibold text-[#1a1a1a]">
                <span className="mr-1 inline-block h-1.5 w-1.5 rounded-[1px] align-middle"
                  style={{ background: categorical[ri % 2] }} />
                {label}
              </td>
              {curve.map((c: any, i: number) => (
                <td key={i} className="border border-[#e0e3e8] px-0.5 py-[2px] text-center tabular-nums text-[#374151]">
                  {pick(c) === null || pick(c) === undefined ? '—' : `${Number(pick(c)).toFixed(2)}%`}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>

      <div className="min-h-0 flex-1">
        <T
          compact
          groups={[{ label: '', span: 1 }, { label: '', span: 1 },
                   { label: 'FTM', span: 2 }, { label: '', span: 1 },
                   { label: '', span: 1 }]}
          head={['Activity', 'Wtg.', 'Plan', 'Actual',
                 'Variance in Plan Vs Actual',
                 'Variance Remark & Mitigation / Action Plan']}
          align={['l', 'r', 'r', 'r', 'r', 'l']} size={9.5}
          widths={[19, 6, 6, 6, 8, 55]}
          rows={[
            ...(project.buckets ?? []).map((b: any) => [
              b.label.split(',')[0], PCT(b.weightPct, 0), PCT(b.planToDatePct, 0),
              PCT(b.earnedPct, 0),
              <span key="v" style={{ color: varColor(b.variancePct), fontWeight: 600 }}>
                {b.variancePct === null ? '—' : `${b.variancePct > 0 ? '+' : ''}${b.variancePct.toFixed(1)}`}
              </span>,
              bucketRemark(b, project),
            ]),
            [<strong key="t">Total</strong>, <strong key="w">100%</strong>,
             <strong key="p">{PCT(plan, 0)}</strong>, <strong key="a">{PCT(actual, 0)}</strong>,
             <strong key="v" style={{ color: varColor(actual - plan) }}>
               {`${actual - plan > 0 ? '+' : ''}${(actual - plan).toFixed(1)}`}
             </strong>,
             <span key="n" className="text-[9.5px] italic leading-tight text-[#6b7280]">
               P6 weightage units, phased on baseline and actual finish dates. The pack reports
               construction on installed physical quantity, tracked outside Akasha, so that row may differ.
             </span>],
          ]}
        />
      </div>
    </div>
  );
};

const milestoneOf = (pkg: any, ...needles: string[]) =>
  pkg.milestones?.find((m: any) => needles.some((n) => m.name.toLowerCase().includes(n)));

/* A date the pack would print even before it happens: actual where the
   milestone is done, P6's current forecast finish where it isn't — never a
   blank just because the work hasn't reached that point yet. The forecast
   half is marked (asterisk in the cell, spelled out once in the footnote)
   so a reader can tell a measurement from a projection at a glance. */
const actualOrForecast = (m: any | null | undefined): [string, boolean] => {
  if (!m) return ['—', false];
  if (m.actualFinish) return [DATE(m.actualFinish), false];
  if (m.forecastFinish) return [`${DATE(m.forecastFinish)}*`, true];
  return ['—', false];
};

const receiptMilestones = (pkg: any) => (pkg.milestones ?? [])
  .filter((m: any) => m.name.toLowerCase().includes('receipt at site'))
  .slice()
  .sort((a: any, b: any) =>
    (a.baselineFinish ?? '').localeCompare(b.baselineFinish ?? ''));

/* MDCC — Manufacturer Document Control Certificate — is a real, literal P6
   milestone (usually several: "MDCC LOT - 1", "MDCC LOT - 2"...). The MDCC
   Date column takes the latest lot, so it reads as "cleared through MDCC up
   to" rather than only the first lot's clearance. */
const mdccMilestones = (pkg: any) => (pkg.milestones ?? [])
  .filter((m: any) => m.name.toLowerCase().trim().startsWith('mdcc'))
  .slice()
  .sort((a: any, b: any) => (a.baselineFinish ?? '').localeCompare(b.baselineFinish ?? ''));

/* The pack's "Forecast Delivery Schedule (Qty)" columns are named for the two
   months after the last one actually reported — not a fixed pair — so a
   project reporting to Sep-26 shows Oct-26/Nov-26, matching what the pack
   itself would print next time it runs. */
const nextMonths = (p: any, n: number): string[] => {
  const curve = p.sCurve ?? [];
  const reported = curve.filter((c: any) => c.actualCumPct !== null).map((c: any) => c.month);
  const last = reported.length ? reported.sort().slice(-1)[0] : null;
  const [y0, m0] = last ? last.split('-').map(Number) : [2026, 9];
  const out: string[] = [];
  let y = y0, m = m0;
  for (let i = 0; i < n; i += 1) {
    m += 1;
    if (m > 12) { m = 1; y += 1; }
    out.push(MONTH_LABEL(`${y}-${String(m).padStart(2, '0')}`));
  }
  return out;
};

const procurementSlide = (p: any): Slide => {
  const [fc1, fc2] = nextMonths(p, 2);
  return {
  id: `proc-${p.pss}`, section: 'Procurement',
  title: `Procurement & Monthly Rolling Plan for Supply of Equipment — ${p.pss}`,
  subtitle: 'P6 ordering milestones joined to SAP purchase orders',
  render: () => {
    const byMat = new Map((p.sap ?? []).map((r: any) => [r.material, r]));
    return (
      <div className="flex h-full flex-col gap-1.5">
      <div className="min-h-0 flex-1 overflow-hidden">
      <T
        /* The pack's own header: three merged groups over paired columns. */
        groups={[
          { label: '', span: 1 }, { label: '', span: 1 }, { label: '', span: 1 },
          { label: '', span: 1 }, { label: '', span: 1 }, { label: '', span: 1 },
          { label: '', span: 1 }, { label: '', span: 1 }, { label: '', span: 1 },
          { label: 'Expected Delivery at Site', span: 2 },
          { label: 'Manufacturing Status', span: 2 },
          { label: '', span: 1 },
          { label: 'Forecast Delivery Schedule (Qty)', span: 2 },
          { label: '', span: 1 },
        ]}
        head={['Sr. No.', 'Packages', 'Manufacturer', 'UOM', 'Scope',
               'Ordering Completed', 'Balance Ordering', 'PO Number', 'PO Date',
               'Start', 'Finish', 'CDD', 'MDCC Date', 'Delivered At Site',
               fc1, fc2, 'Remarks']}
        align={['r', 'l', 'l', 'l', 'r', 'r', 'r', 'l', 'l', 'l', 'l', 'l', 'l',
                'r', 'r', 'r', 'l']}
        size={8}
        widths={[2.5, 10.5, 10, 3.5, 4, 5.5, 5.5, 9.5, 5, 4.5, 4.5, 6, 5, 5, 3.5, 3.5, 12.7]}
        colTint={[...Array(9).fill('grey'), ...Array(8).fill('peach')]}
        rows={(p.packages ?? []).map((pkg: any, i: number) => {
          const order = milestoneOf(pkg, 'placement of the order');
          const mdcc = mdccMilestones(pkg);
          const receipts = receiptMilestones(pkg);
          const done = receipts.filter((m: any) => m.actualFinish);
          const slips = (pkg.milestones ?? []).map((m: any) => m.slipDays)
            .filter((x: any) => x !== null && x !== undefined);
          const worst = slips.length ? Math.max(...slips) : null;
          const sap: any = byMat.get(pkg.sapMaterial ?? '');
          const ordered = sap?.orderQtyRaw ?? null;
          const scope = pkg.scopeQty ?? null;
          const [poDate] = actualOrForecast(order);
          // MDCC Date: the latest lot cleared, actual where cleared, P6's own
          // forecast where it hasn't been yet. CDD has no matching P6
          // milestone (checked: no activity literally named "CDD" exists),
          // so it stays blank rather than guessed.
          const [mdccDate] = mdcc.length ? actualOrForecast(mdcc[mdcc.length - 1]) : ['—', false];
          // Expected Delivery at Site: first and last "Receipt at Site" lot,
          // actual where landed, P6's own forecast where it hasn't yet.
          const [deliveryStart] = receipts.length ? actualOrForecast(receipts[0]) : ['—', false];
          const [deliveryFinish] = receipts.length ? actualOrForecast(receipts[receipts.length - 1]) : ['—', false];
          const lastLanded = [...done].sort((a, b) =>
            (a.actualFinish ?? '').localeCompare(b.actualFinish ?? '')).pop();
          const remark = [
            receipts.length ? `${done.length} of ${receipts.length} lots received` : null,
            lastLanded ? `last ${DATE(lastLanded.actualFinish)}` : null,
            worst !== null && worst > 0 ? `worst slip +${worst}d` : null,
          ].filter(Boolean).join('; ') || '—';
          return [
            String(i + 1),
            pkg.packageBase ?? pkg.package,
            sap?.vendor ?? '—',
            pkg.uom ?? (scope ? 'Nos.' : '—'),
            scope !== null ? NUM(scope) : '—',
            ordered !== null ? NUM(ordered) : '—',
            /* Balance is only meaningful when both sides are known and share a
               unit; SAP quantities mix units across multi-line POs. */
            scope !== null && ordered !== null && sap?.material === 'BESS Containers'
              ? NUM(Math.max(scope - ordered, 0)) : '—',
            sap?.poNumbers ?? '—',
            poDate,
            deliveryStart, deliveryFinish,
            '—', mdccDate,
            sap?.deliveredQtyRaw ? NUM(sap.deliveredQtyRaw) : '—',
            '—', '—',
            remark,
          ];
        })}
      />
      </div>
      <p className="shrink-0 text-[10px] italic leading-snug text-[#6b7280]">
        {p.sapNote || (p.sapAvailable
          ? 'SAP holds no PO date or delivery date for these projects, so dates are P6 ordering milestones; manufacturer, PO number and delivered quantity are from SAP.'
          : 'SAP has no purchase orders for this project in the current extract; dates below are P6 ordering milestones only.')}
        {' '}* forecast (not yet actual) — P6’s current schedule finish for that milestone.
      </p>
      </div>
    );
  },
  };
};

/* The reference pack's approvals table is nine columns ending in a single
   Remarks column — there is no separate slip column. Slip is real and useful,
   so rather than add an eleventh column the pack doesn't have, it is folded
   into the words of Remarks the way the pack folds its own commentary in. */
const approvalRemark = (a: any): string => {
  if (a.status === 'Completed') {
    const slip = a.slipDays;
    if (slip === null || slip === undefined || slip <= 0) return `Completed ${DATE(a.actualFinish)}.`;
    return `Completed ${DATE(a.actualFinish)} — ${slip}d behind baseline.`;
  }
  if (a.status === 'In Progress') return 'In progress.';
  if (a.forecastFinish) return `Forecast ${DATE(a.forecastFinish)}.`;
  return '—';
};

const approvalsSlide = (p: any, from: number, to: number, page: string): Slide => ({
  id: `appr-${p.pss}-${page}`, section: 'Approvals',
  title: `Statutory and Other Approvals (${p.pss})`,
  subtitle: `${p.approvalsDone} of ${p.approvalsTotal} complete · ${page}`,
  render: () => (
    <T
      head={['SN', 'Activity Name', 'Responsible', 'Approval Authority',
             'Baseline Start', 'Baseline Finish', 'Actual/ Forecast Start',
             'Actual/ Forecast Finish', 'Remarks']}
      align={['r', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l']} size={10}
      widths={[3, 24, 9, 11, 9, 9, 10, 11, 14]}
      rows={(p.approvals ?? []).slice(from, to).map((a: any, i: number) => [
        String(from + i + 1), a.name, '—', '—',
        DATE(a.baselineStart), DATE(a.baselineFinish), DATE(a.actualStart),
        DATE(a.actualFinish ?? a.forecastFinish),
        approvalRemark(a),
      ])}
    />
  ),
});

const mandaysSlide = (man: any, label: string): Slide => ({
  id: 'mandays', section: 'Manpower',
  title: `Mandays Deployment Plan vs Actual — ${label}`,
  subtitle: 'Planned Labor units against earned mandays',
  render: () => <MandaysBody man={man} />,
});

const MandaysBody: React.FC<{ man: any }> = ({ man }) => {
  const { categorical, chrome } = useChartTheme();
  const s = man.series ?? [];
  const option = useMemo(() => ({
    grid: { left: 54, right: 54, top: 26, bottom: 24, containLabel: true },
    tooltip: { trigger: 'axis', valueFormatter: (v: number) => NUM(v) },
    legend: { show: true, top: 0, right: 0, itemWidth: 13, itemHeight: 8, itemGap: 12 },
    xAxis: { type: 'category', data: s.map((m: any) => MONTH_LABEL(m.month)) },
    yAxis: [
      { type: 'value', name: 'Monthly' },
      { type: 'value', name: 'Cumulative', splitLine: { show: false } },
    ],
    series: [
      { name: 'Monthly plan', type: 'bar', barWidth: '26%',
        data: s.map((m: any) => m.planMonth),
        itemStyle: { color: categorical[0], borderRadius: [2, 2, 0, 0] } },
      { name: 'Monthly earned', type: 'bar', barWidth: '26%',
        data: s.map((m: any) => m.earnedMonth),
        itemStyle: { color: categorical[1], borderRadius: [2, 2, 0, 0] } },
      { name: 'Cumulative plan', type: 'line', yAxisIndex: 1, symbol: 'none', smooth: 0.25,
        data: s.map((m: any) => m.planCum),
        lineStyle: { width: 2.2, color: categorical[0] },
        itemStyle: { color: categorical[0] } },
      { name: 'Cumulative earned', type: 'line', yAxisIndex: 1, symbol: 'none', smooth: 0.25,
        data: s.map((m: any) => m.earnedCum),
        lineStyle: { width: 2.6, color: categorical[1] },
        itemStyle: { color: categorical[1] } },
    ],
  }), [s, categorical, chrome]);
  const planned = man.totalPlannedMandays ?? 0;
  const earned = man.earnedMandays ?? 0;
  const months = s.map((m: any) => MONTH_LABEL(m.month));

  /* Same layout as the S-curve and Financial slides: chart and summary on
     top, then the per-month figures spelled out in a grid underneath, so a
     reader can take a number off the table without reading the chart. */
  return (
    <div className="flex h-full flex-col gap-1.5">
      <div className="grid min-h-0 flex-[1.3] grid-cols-[1.4fr_1fr] gap-6">
        <div className="min-w-0"><Chart option={option} height={230} /></div>
        <T head={['Measure', 'Mandays']} align={['l', 'r']} size={12}
          rows={[
            ['Scope (planned Labor units)', NUM(planned)],
            ['Earned (scope × % complete)', NUM(earned)],
            ['Remaining', NUM(planned - earned)],
            ['Earned %', PCT(planned ? (earned / planned) * 100 : null)],
            ['Posted actual units', NUM(man.postedActualUnits ?? 0)],
          ]} />
      </div>
      <table className="w-full shrink-0 table-fixed border-collapse text-[8.5px]">
        <colgroup>
          <col style={{ width: '14%' }} />
          {months.map((_: string, i: number) => (
            <col key={i} style={{ width: `${86 / Math.max(months.length, 1)}%` }} />
          ))}
        </colgroup>
        <thead>
          <tr>
            <th className="border border-[#c9ccd2] bg-[#f6f7f9] px-1 py-1" />
            {months.map((m: string) => (
              <th key={m} className="border border-[#c9ccd2] bg-[#f6f7f9] px-0.5 py-1 text-center font-semibold text-[#1a1a1a]">
                {m}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {([
            ['Planned (month)', (m: any) => m.planMonth],
            ['Earned (month)', (m: any) => m.earnedMonth],
            ['Planned cum.', (m: any) => m.planCum],
            ['Earned cum.', (m: any) => m.earnedCum],
          ] as [string, (m: any) => number][]).map(([rowLabel, pick]) => (
            <tr key={rowLabel}>
              <td className="border border-[#c9ccd2] px-1 py-[3px] font-semibold text-[#1a1a1a]">
                {rowLabel}
              </td>
              {s.map((m: any, i: number) => (
                <td key={i} className="border border-[#c9ccd2] px-0.5 py-[3px] text-center tabular-nums text-[#374151]">
                  {NUM(pick(m), 0)}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
      <p className="shrink-0 text-[9.5px] italic leading-snug text-[#6b7280]">
        Scope is planned Labor units (mandays) on the schedule. Earned = scope × activity percent
        complete — the same percent that drives physical progress — because actual labour units are
        not posted in P6 (1–4 non-zero rows out of 1,300–3,300 per project). This shows mandays
        credited for work done, not workmen deployed, and cannot reveal a productivity gap.
      </p>
    </div>
  );
};

const manpowerCurveSlide = (man: any, label: string): Slide => ({
  id: 'manpower-curve', section: 'Manpower',
  title: `Manpower Deployment Plan vs Actual — ${label}`,
  subtitle: 'Cumulative mandays',
  render: () => <ManpowerCurveBody man={man} />,
});

const ManpowerCurveBody: React.FC<{ man: any }> = ({ man }) => {
  const { categorical } = useChartTheme();
  const s = man.series ?? [];
  const option = useMemo(() => ({
    grid: { left: 62, right: 22, top: 26, bottom: 24, containLabel: true },
    tooltip: { trigger: 'axis', valueFormatter: (v: number) => NUM(v) },
    legend: { show: true, top: 0, right: 0, itemWidth: 13, itemHeight: 8 },
    xAxis: { type: 'category', boundaryGap: false, data: s.map((m: any) => MONTH_LABEL(m.month)) },
    yAxis: { type: 'value' },
    series: [
      { name: 'Cumulative plan', type: 'line', symbol: 'none', smooth: 0.25,
        data: s.map((m: any) => m.planCum),
        lineStyle: { width: 2.2, color: categorical[0] },
        itemStyle: { color: categorical[0] } },
      { name: 'Cumulative earned', type: 'line', symbol: 'none', smooth: 0.25,
        data: s.map((m: any) => m.earnedCum),
        lineStyle: { width: 2.6, color: categorical[1] },
        itemStyle: { color: categorical[1] },
        areaStyle: { opacity: 0.08, color: categorical[1] } },
    ],
  }), [s, categorical]);
  return (
    <div className="flex h-full flex-col gap-3">
      <div className="min-h-0 flex-1"><Chart option={option} height={380} /></div>
      <p className="shrink-0 text-[11px] italic leading-snug text-[#6b7280]">
        Average headcount can be read as mandays divided by working days in the month. Contractor-level
        deployment is not held in any connected system.
      </p>
    </div>
  );
};

const financialSlide = (financial: any, label: string): Slide => ({
  id: 'financial', section: 'Commercial', title: 'Financial S Curve',
  subtitle: label,
  render: () => <FinancialBody financial={financial} />,
});

/* The pack's own layout: one combo chart (monthly bars behind cumulative
   lines, both series) then a four-row month grid underneath it - Budgeted
   cumulative / Monthly Budgeted / Actual Cumulative / Monthly Actual - not
   the per-PSS ordered/delivered table this used to substitute. */
const FinancialBody: React.FC<{ financial: any }> = ({ financial }) => {
  const { categorical } = useChartTheme();
  const s = financial?.series ?? [];
  const months = s.map((m: any) => MONTH_LABEL(m.month));

  const option = useMemo(() => ({
    grid: { left: 54, right: 58, top: 26, bottom: 22, containLabel: true },
    tooltip: { trigger: 'axis', valueFormatter: (v: number) => `₹${NUM(v, 1)} Cr` },
    legend: { show: true, top: 0, right: 0, itemWidth: 13, itemHeight: 8, itemGap: 12 },
    xAxis: { type: 'category', data: months },
    yAxis: [{ type: 'value', name: '₹ Cr (monthly)' },
            { type: 'value', name: '₹ Cr (cumulative)', splitLine: { show: false } }],
    series: [
      { name: 'Monthly Budgeted', type: 'bar', barWidth: '26%',
        data: s.map((m: any) => m.budgetedMonthCr),
        itemStyle: { color: categorical[0], borderRadius: [2, 2, 0, 0] } },
      { name: 'Monthly Actual', type: 'bar', barWidth: '26%',
        data: s.map((m: any) => m.actualMonthCr),
        itemStyle: { color: categorical[1], borderRadius: [2, 2, 0, 0] } },
      { name: 'Budgeted cumulative', type: 'line', yAxisIndex: 1, symbol: 'none', smooth: 0.25,
        data: s.map((m: any) => m.budgetedCumCr),
        lineStyle: { width: 2.2, type: 'dashed', color: categorical[0] },
        itemStyle: { color: categorical[0] } },
      { name: 'Actual cumulative', type: 'line', yAxisIndex: 1, symbol: 'none', smooth: 0.25,
        data: s.map((m: any) => m.actualCumCr),
        lineStyle: { width: 2.6, color: categorical[1] },
        itemStyle: { color: categorical[1] } },
    ],
  }), [s, months, categorical]);

  return (
    <div className="flex h-full flex-col gap-1.5">
      <div className="shrink-0"><Chart option={option} height={260} /></div>
      <div className="min-h-0 flex-1 overflow-hidden">
        <table className="w-full table-fixed border-collapse text-[8.5px]">
          <colgroup>
            <col style={{ width: '13%' }} />
            {months.map((_: string, i: number) => (
              <col key={i} style={{ width: `${87 / Math.max(months.length, 1)}%` }} />
            ))}
          </colgroup>
          <thead>
            <tr>
              <th className="border border-[#c9ccd2] bg-[#f6f7f9] px-1 py-1" />
              {months.map((m: string) => (
                <th key={m} className="border border-[#c9ccd2] bg-[#f6f7f9] px-0.5 py-1 text-center font-semibold text-[#1a1a1a]">
                  {m}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {([
              ['Budgeted- cumulative', (m: any) => m.budgetedCumCr],
              ['Monthly Budgeted', (m: any) => m.budgetedMonthCr],
              ['Actual Cumulative', (m: any) => m.actualCumCr],
              ['Monthly Actual', (m: any) => m.actualMonthCr],
            ] as [string, (m: any) => number][]).map(([rowLabel, pick]) => (
              <tr key={rowLabel}>
                <td className="border border-[#c9ccd2] px-1 py-[3px] font-semibold text-[#1a1a1a]">
                  {rowLabel}
                </td>
                {s.map((m: any, i: number) => (
                  <td key={i} className="border border-[#c9ccd2] px-0.5 py-[3px] text-center tabular-nums text-[#374151]">
                    {NUM(pick(m), 0)}
                  </td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      <p className="shrink-0 text-[9.5px] italic leading-snug text-[#6b7280]">
        Budgeted is derived, not measured: the ₹16,358 Cr approved NFA (NFA_R1, 04-Apr-26) spread
        across each project&rsquo;s own P6 baseline schedule, weighted by dispatchable MWh share — a
        schedule projection onto a real total, not a cost-loaded plan. Actual is SAP goods-receipt
        value and reads zero portfolio-wide because mt_materialdocument, the only source with a
        posting date to phase it by month, holds no rows at this sync.
      </p>
    </div>
  );
};

const contractorSlide = (p: any): Slide => ({
  id: `contractors-${p.pss}`, section: 'Manpower',
  title: `Contractor Status (${p.pss})`,
  subtitle: 'Contracted scope and quality record',
  render: () => (
    <T
      head={['Contractor', 'POs', 'Contracted ₹Cr', 'Delivered ₹Cr', 'Delivered %',
             'RFIs', 'NCs', 'NC rate']}
      align={['l', 'r', 'r', 'r', 'r', 'r', 'r', 'r']} size={12}
      widths={[32, 6, 13, 13, 11, 8, 7, 10]}
      rows={(p.contractors ?? []).filter((c: any) => c.kind === 'site').slice(0, 13)
        .map((c: any) => [c.vendor, String(c.poCount), NUM(c.orderCr, 2),
          NUM(c.deliveredCr, 2), PCT(c.deliveredPct, 0),
          c.rfiCount || '—', c.ncCount || '—',
          <span key="n" style={{ color: c.ncRatePct >= 25 ? '#d92d20'
            : c.ncRatePct >= 10 ? '#f79009' : '#1a1a1a', fontWeight: 600 }}>
            {PCT(c.ncRatePct, 1)}
          </span>])}
    />
  ),
});

/* Supply and Service are two different WBS branches ("Ordering & Delivery"
   and "Service Order"), reported on separate slides in the pack. Reading the
   split off which packages happen to have a SAP price match would put a
   civil/consultancy service on the wrong slide whenever a supply item's SAP
   line was missing — so the split follows the WBS branch each package
   actually came from, not a guess from SAP presence. */
const buildOrderingRows = (group: any[], kind: string): any[][] => {
  const rows: any[][] = [];
  group.forEach((p) => {
    const byMat = new Map((p.sap ?? []).map((r: any) => [r.material, r]));
    const pkgs = kind === 'Supply' ? (p.packages ?? []) : (p.servicePackages ?? []);
    pkgs.forEach((pkg: any) => {
      const sap: any = byMat.get(pkg.sapMaterial ?? '');
      const order = milestoneOf(pkg, 'placement of the order');
      const [releaseDate] = actualOrForecast(order);
      rows.push([
        `${pkg.packageBase ?? pkg.package} (${p.pss})`,
        pkg.scopeQty ? `${NUM(pkg.scopeQty)} nos` : '—',
        '—',
        /* The pack always prints "NA" in this column for every package —
           reproduced literally rather than left blank, since that is what
           the reference itself shows. */
        'NA',
        '—', '—', '—', '—',
        releaseDate,
        sap ? `${sap.vendor} · ₹${NUM(sap.orderCr, 1)} Cr` : '—',
      ]);
    });
  });
  return rows;
};

const ORDERING_PAGE_SIZE = 9;

const orderingSlide = (rows: any[][], startAt: number, total: number,
                       kind: string, gl: string, page: string): Slide => ({
  id: `ordering-${kind}-${gl}-${startAt}`, section: 'Ordering status',
  title: `${kind} ordering Status (${gl})`,
  subtitle: `${kind} packages · ${page} · ${total} total`,
  render: () => (
    <div className="flex h-full flex-col gap-1.5">
      <div className="min-h-0 flex-1">
        <T
          head={['SN', 'Equipment/ Package', 'Qty / Scope',
                 'Final / Revised Specifications Issue Date',
                 'Verified by Engineering Consultant', 'TBER Date',
                 'Qualified Vendors', 'Receipt of Offer',
                 'Commercial NFA Submission', 'Release of PO / SO', 'Update']}
          align={['r', 'l', 'r', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l']} size={10}
          widths={[3, 16, 7, 10, 9, 8, 10, 8, 9, 10, 10]}
          rows={rows.map((r, i) => [String(startAt + i + 1), ...r])}
        />
      </div>
      <p className="shrink-0 text-[10px] italic leading-snug text-[#6b7280]">
        Specification issue date, TBER date, qualified vendor list, receipt of
        offer and commercial NFA submission are not held in any connected
        system and are left blank. Release of PO/SO is the P6 order-placement
        milestone; * marks a forecast date where the order has not yet been
        placed. Vendor and value come from SAP.
      </p>
    </div>
  ),
});

/* ── Viewer ── */
export const CPAGSlideViewer: React.FC<{
  slides: Slide[];
  deckTitle: string;
  downloadHref: string;
  onClose?: () => void;
}> = ({ slides, deckTitle, downloadHref, onClose }) => {
  const [index, setIndex] = useState(0);
  const [full, setFull] = useState(false);
  const [showIndex, setShowIndex] = useState(false);
  const stageRef = useRef<HTMLDivElement>(null);
  const [scale, setScale] = useState(1);

  const total = slides.length;
  const next = useCallback(() => setIndex((i) => Math.min(i + 1, total - 1)), [total]);
  const prev = useCallback(() => setIndex((i) => Math.max(i - 1, 0)), []);

  /* The board is authored at a fixed size, so it is scaled to whatever the
     stage measures rather than reflowed. */
  useEffect(() => {
    const el = stageRef.current;
    if (!el) return;
    const fit = () => {
      const { width, height } = el.getBoundingClientRect();
      setScale(Math.min(width / BOARD_W, height / BOARD_H));
    };
    fit();
    const ro = new ResizeObserver(fit);
    ro.observe(el);
    return () => ro.disconnect();
  }, [full]);

  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'ArrowRight' || e.key === 'PageDown') { e.preventDefault(); next(); }
      if (e.key === 'ArrowLeft' || e.key === 'PageUp') { e.preventDefault(); prev(); }
      if (e.key === 'Home') setIndex(0);
      if (e.key === 'End') setIndex(total - 1);
      if (e.key === 'Escape') { if (full) setFull(false); else onClose?.(); }
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [next, prev, total, full, onClose]);

  const slide = slides[index];

  /* Section groupings for the jump list — 69 slides is too many for dots. */
  const sections = useMemo(() => {
    const map: { section: string; items: { i: number; title: string }[] }[] = [];
    slides.forEach((s, i) => {
      const last = map[map.length - 1];
      if (!last || last.section !== s.section) map.push({ section: s.section, items: [] });
      map[map.length - 1].items.push({ i, title: s.title });
    });
    return map;
  }, [slides]);

  return (
    <div className={cx('flex flex-col', full
      ? 'fixed inset-0 z-[120] bg-white'
      : 'rounded-xl border border-slate-200 bg-white')}>
      {/* Chrome */}
      <div className="flex shrink-0 items-center justify-between gap-3 border-b border-slate-200 px-4 py-2.5 bg-white rounded-t-xl">
        <div className="flex min-w-0 items-center gap-3">
          <button
            onClick={() => setShowIndex((v) => !v)}
            aria-label="Slide index"
            className="rounded-lg p-1.5 text-slate-500 transition-colors hover:bg-slate-100 hover:text-slate-900
                       focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-slate-400">
            <List className="h-[18px] w-[18px]" strokeWidth={1.5} />
          </button>
          <span className="rounded-full border border-primary/30 bg-primary/10 px-2.5 py-1 text-[11px] font-semibold text-primary">
            {index + 1} / {total}
          </span>
          <p className="truncate text-[13px] font-medium text-slate-700">{deckTitle}</p>
        </div>
        <div className="flex shrink-0 items-center gap-1.5">
          <a
            href={downloadHref}
            className="flex items-center gap-1.5 rounded-lg border border-slate-200 px-2.5 py-1.5 text-[12px]
                       font-medium text-slate-700 transition-colors hover:bg-slate-100 hover:text-slate-900
                       focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-slate-400">
            <Download className="h-3.5 w-3.5" strokeWidth={1.5} /> .pptx
          </a>
          <button
            onClick={() => setFull((v) => !v)}
            aria-label={full ? 'Exit full screen' : 'Full screen'}
            className="rounded-lg p-1.5 text-slate-500 transition-colors hover:bg-slate-100 hover:text-slate-900
                       focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-slate-400">
            {full ? <Minimize2 className="h-[18px] w-[18px]" strokeWidth={1.5} />
                  : <Maximize2 className="h-[18px] w-[18px]" strokeWidth={1.5} />}
          </button>
          {onClose && (
            <button
              onClick={onClose} aria-label="Close"
              className="rounded-lg p-1.5 text-slate-500 transition-colors hover:bg-slate-100 hover:text-slate-900
                         focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-slate-400">
              <X className="h-[18px] w-[18px]" strokeWidth={1.5} />
            </button>
          )}
        </div>
      </div>

      <div className="flex min-h-0 flex-1">
        {/* Jump list */}
        <AnimatePresence initial={false}>
          {showIndex && (
            <motion.nav
              initial={{ width: 0, opacity: 0 }}
              animate={{ width: 252, opacity: 1 }}
              exit={{ width: 0, opacity: 0 }}
              transition={{ duration: 0.18 }}
              className="custom-scrollbar shrink-0 overflow-y-auto border-r border-slate-200 bg-white">
              <div className="w-[252px] py-2">
                {sections.map((sec) => (
                  <div key={sec.section} className="mb-1">
                    <p className="px-3 py-1.5 text-[10px] font-bold uppercase tracking-wider text-slate-400">
                      {sec.section}
                    </p>
                    {sec.items.map((it) => (
                      <button
                        key={it.i}
                        onClick={() => setIndex(it.i)}
                        className={cx('block w-full truncate px-3 py-1.5 text-left text-[12px] transition-colors',
                          it.i === index ? 'bg-primary/10 font-semibold text-primary'
                            : 'text-slate-600 hover:bg-slate-50 hover:text-slate-900')}>
                        <span className="mr-2 tabular-nums text-slate-400">{it.i + 1}</span>
                        {it.title}
                      </button>
                    ))}
                  </div>
                ))}
              </div>
            </motion.nav>
          )}
        </AnimatePresence>

        {/* Stage */}
        <div ref={stageRef}
          className={cx('relative min-w-0 flex-1 overflow-hidden bg-slate-50',
            full ? '' : 'h-[min(72vh,760px)]')}>
          <AnimatePresence mode="wait">
            <motion.div
              key={slide.id}
              initial={{ opacity: 0, x: 18 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: -18 }}
              transition={{ duration: 0.22 }}
              className="absolute inset-0 flex items-center justify-center">
              <div
                style={{ transform: `scale(${scale})`, transformOrigin: 'center' }}
                className="shadow-[0_0_60px_rgba(0,0,0,0.55)]">
                {slide.section === 'Cover' || slide.section === 'Divider' || slide.section === 'Close'
                  ? slide.render()
                  : (
                    <Board title={slide.title} subtitle={slide.subtitle}
                      index={index + 1} total={total}>
                      {slide.render()}
                    </Board>
                  )}
              </div>
            </motion.div>
          </AnimatePresence>

          <button
            onClick={prev} disabled={index === 0} aria-label="Previous slide"
            className="absolute left-3 top-1/2 -translate-y-1/2 rounded-full bg-black/40 p-2.5 text-white/70
                       opacity-0 transition hover:bg-black/70 hover:text-white focus-visible:opacity-100
                       disabled:pointer-events-none disabled:opacity-0 [.group:hover_&]:opacity-100
                       md:opacity-60">
            <ChevronLeft className="h-5 w-5" strokeWidth={1.75} />
          </button>
          <button
            onClick={next} disabled={index === total - 1} aria-label="Next slide"
            className="absolute right-3 top-1/2 -translate-y-1/2 rounded-full bg-black/40 p-2.5 text-white/70
                       opacity-0 transition hover:bg-black/70 hover:text-white focus-visible:opacity-100
                       disabled:pointer-events-none disabled:opacity-0 md:opacity-60">
            <ChevronRight className="h-5 w-5" strokeWidth={1.75} />
          </button>
        </div>
      </div>

      {/* Progress rail */}
      <div className="shrink-0 border-t border-slate-200 px-4 py-2 bg-white rounded-b-xl">
        <div className="flex items-center gap-3">
          <div className="h-1 flex-1 overflow-hidden rounded-full bg-slate-100">
            <div className="h-full rounded-full bg-primary transition-[width] duration-300"
              style={{ width: `${((index + 1) / total) * 100}%` }} />
          </div>
          <span className="flex items-center gap-1.5 text-[11px] text-slate-400">
            <Info className="h-3 w-3" strokeWidth={1.5} />
            Arrow keys to navigate
          </span>
        </div>
      </div>
    </div>
  );
};

export default CPAGSlideViewer;
