"""
CPAG pack as a .pptx, on Adani's own template.

Composes the deck in the circulated pack's running order. The template in
assets/cpag_template.pptx is that pack with its slides stripped out — masters,
layouts, theme, fonts and brand furniture kept — so the output opens looking
like the deck reviewers already read rather than a lookalike.

Two rules govern what appears:

* **Every slide in the sequence is issued.** Where no connected system holds a
  slide's data it is still produced, titled and in position, stating what is
  missing and what would fill it. Reviewers navigate this pack by slide
  position, and a deck that quietly dropped slides would read as if the pack
  had shrunk rather than as a reporting gap.
* **Selecting one project shortens the deck, not the slides.** The per-project
  sections collapse from six to one; every slide that does appear carries the
  same columns, built by the same functions.
"""
from io import BytesIO
from typing import Any, Dict, List

from services.cpag_pptx_base import _date, _deck, _section_slide, _month
from services import cpag_slides as S


def _plan_totals(project: Dict[str, Any]) -> tuple:
    """Plan-to-date and actual for a project, however the payload spells it."""
    buckets = project.get("buckets") or []
    plan = project.get("planToDatePct")
    if plan is None:
        plan = sum(b.get("planToDatePct") or 0.0 for b in buckets)
    actual = project.get("actualPct")
    if actual is None:
        actual = sum(b.get("earnedPct") or 0.0 for b in buckets)
    return plan, actual


def _group_label(projects: List[Dict[str, Any]]) -> str:
    return ", ".join(p["pss"] for p in projects) if projects else "-"


def _fmt_qty(v) -> str:
    return f"{v:,} nos" if isinstance(v, (int, float)) and v else "-"


def _order_date(m) -> str:
    """Actual finish where the order has been placed; P6's own forecast where
    it hasn't - never blank just because the milestone is still ahead."""
    if not m:
        return "-"
    if m.get("actualFinish"):
        return _date(m["actualFinish"])
    if m.get("forecastFinish"):
        return f"{_date(m['forecastFinish'])}*"
    return "-"


ORDERING_PAGE_SIZE = 9


def _ordering_rows(projects: List[Dict[str, Any]], kind: str) -> List[List[str]]:
    """Ordering-status rows: what SAP and P6 hold, blanks where nothing does.

    Supply and Service are two different WBS branches ("Ordering & Delivery"
    and "Service Order"), which the pack reports on separate slides - the
    split follows the branch each package actually came from (`packages` vs
    `servicePackages`), not a guess from whether a SAP price happens to exist
    for it, which would misfile a service item whenever its supply sibling's
    SAP line was missing.

    "Verified by Engineering Consultant" is always "NA" in the circulated
    pack, so it is reproduced literally rather than left blank.
    """
    rows: List[List[str]] = []
    key = "packages" if kind == "supply" else "servicePackages"
    for p in projects:
        by_material = {r["material"]: r for r in (p.get("sap") or [])}
        for pkg in p.get(key) or []:
            sap_row = by_material.get(pkg.get("sapMaterial") or "")
            order = None
            for m in pkg["milestones"]:
                if "placement of the order" in m["name"].lower():
                    order = m
                    break
            rows.append([
                f"{pkg.get('packageBase') or pkg.get('package')} ({p['pss']})",
                _fmt_qty(pkg.get("scopeQty")),
                "-", "NA", "-", "-", "-", "-",
                _order_date(order),
                (f"{sap_row['vendor']} · Rs {sap_row['orderCr']} Cr"
                 if sap_row else "-"),
            ])
    return rows


def _compose(prs, projects: List[Dict[str, Any]], meta: Dict[str, Any],
             commercial: Dict[str, Any], manpower: Dict[str, Any],
             financial: Dict[str, Any],
             *, single: bool) -> None:
    """The pack's running order, over however many projects are in scope."""
    label = _group_label(projects)
    half = max(1, (len(projects) + 1) // 2)
    group_a, group_b = projects[:half], projects[half:]
    groups = [g for g in (group_a, group_b) if g]

    # Cover
    if single:
        p0 = projects[0]
        cover_title = f"{p0['pss']} — CPAG Report"
        cover_sub = (f"{p0['spv']} · Plot {p0.get('plot') or '—'} · "
                     f"{p0['powerMw']:,} MW / {p0['energyMwh']:,} MWh")
    else:
        cover_title = "Battery Energy Storage Systems — CPAG Report"
        cover_sub = (f"{len(projects)} projects · {meta['powerMw']:,} MW / "
                     f"{meta['energyMwh']:,} MWh · FY 2026-27")
    month_str = _month(meta.get("lastActualMonth")) if meta.get("lastActualMonth") else "—"
    stamp = f"Khavda RE Park, Gujarat · reported to {month_str} · generated by Akasha from P6, SAP and Pulse"
    S._cover(prs, cover_title, cover_sub, stamp)

    # Portfolio tables
    S.slide_capacity(prs, projects, meta)
    S.slide_salient(prs, projects, meta, commercial)

    S._unavailable(
        prs, "Overall Layout", label,
        "Plot geometry for the BESS parcels is not held in any connected system.",
        "Would need the Khavda park layout drawing with plot boundaries.")

    if any((p.get("commissioning") or {}).get("items") for p in projects):
        S.slide_commissioning_all(prs, projects, label)
    else:
        S._unavailable(
            prs, "Commissioning Plan", label,
            "The month-by-month MWh and container commissioning plan has no "
            "system of record.",
            "P6 carries commissioning activities and dates, but not the MWh or "
            "container quantity released in each month.")

    # Physical progress — one slide per project
    for p in projects:
        plan, actual = _plan_totals(p)
        S.slide_scurve(prs, p["pss"], p["spv"], p.get("sCurve") or [],
                       p.get("buckets") or [], plan, actual, project=p)

    if any((p.get("engineering") or {}).get("total") for p in projects):
        S.slide_engineering_all(prs, projects, label)
    else:
        S._unavailable(
            prs, "Engineering Progress", label,
            "The engineering master document log - total documents, cumulative "
            "received and approvals by category - is not ingested.",
            "Would need the Phase-II master log from SharePoint.")

    # Procurement
    _section_slide(prs, f"Procurement Status: {label}")
    for p in projects:
        S.slide_procurement(prs, p["pss"], p.get("packages") or [],
                            p.get("sap") or [], p.get("sapNote"), project=p)

    # Construction progress — element level
    for group in groups:
        _section_slide(prs, f"{_group_label(group)} Progress")
        for p in group:
            con = p.get("construction") or {}
            if con.get("elements"):
                S.slide_civil(prs, p["pss"], p["spv"], con)
            else:
                S._unavailable(
                    prs, f"Civil Construction Progress (Plan vs Actual) ({p['pss']})",
                    p["spv"],
                    "Element-level civil progress is measured on installed "
                    "physical quantity.",
                    "P6 Material resources hold these under the Construction "
                    "branches.")
            elec = p.get("electrical") or {}
            if elec.get("items"):
                S.slide_electrical(prs, p["pss"], p["spv"], elec)
            else:
                S._unavailable(
                    prs, f"Electrical Plan Vs Actual Summary {p['pss']}",
                    p["spv"],
                    "Element-level electrical progress is reported on running "
                    "metres laid and units erected.",
                    "P6 Material resources hold these under the Construction "
                    "branches.")

    # Manpower
    _section_slide(prs, f"Manpower & Mandays Status: {label}")
    S.slide_mandays(prs, manpower.get("series") or [],
                    manpower.get("totalPlannedMandays") or 0,
                    manpower.get("earnedMandays") or 0, label,
                    manpower.get("postedActualUnits"))
    S.slide_manpower_curve(prs, manpower.get("series") or [], label)
    for p in projects:
        if p.get("contractors"):
            S.slide_contractors(prs, p["pss"], p["contractors"],
                                p.get("contractorNote") or "")
        else:
            S._unavailable(
                prs, f"Contractor Manpower Status ({p['pss']})", p["spv"],
                "Contractor headcount by month — forecast, actual and shortfall "
                "— is not held in any connected system.",
                "Contractor identity exists in SAP and Pulse; the deployed and "
                "required headcount does not.")

    if any((p.get("quality") or {}).get("rfiTotal") for p in projects):
        S.slide_quality_all(prs, projects, label)

    S._unavailable(
        prs, "Major Milestones - Next 3 Months", label,
        "The forward milestone commitments, with delivery quantities per month, "
        "are compiled manually for the review.",
        "P6 holds the milestone dates; the container and PCS quantities promised "
        "per month have no source.")
    S._unavailable(
        prs, "Critical Issues FY 26-27", label,
        "The issue register — impact, corrective action, owner and support "
        "required — is narrative and has no system of record.",
        "Variance and slip are measured throughout this pack; the commentary "
        "around them is not.")

    S.slide_financial(prs, financial or {}, label)

    # Ordering status - paginated, since a group of three projects runs to
    # 45+ supply packages and one slide's worth would silently drop the rest.
    for group in groups:
        gl = _group_label(group)
        _section_slide(prs, f"Ordering Status {gl}")
        for kind_label, kind_key in (("Supply", "supply"), ("Service", "service")):
            rows = _ordering_rows(group, kind_key)
            page_count = max(1, -(-len(rows) // ORDERING_PAGE_SIZE))
            for pg in range(page_count):
                chunk = rows[pg * ORDERING_PAGE_SIZE:(pg + 1) * ORDERING_PAGE_SIZE]
                numbered = [[str(pg * ORDERING_PAGE_SIZE + i + 1), *r]
                            for i, r in enumerate(chunk)]
                S.slide_ordering_status(
                    prs, gl, kind_label, numbered,
                    f"{kind_label} packages - page {pg + 1} of {page_count} "
                    f"- {len(rows)} total")

    # Statutory approvals — two pages per project, as the pack runs them
    for group in groups:
        _section_slide(prs, f"Statutory & Other approvals {_group_label(group)}")
        for p in group:
            items = p.get("approvals") or []
            done = p.get("approvalsDone", 0)
            total = p.get("approvalsTotal", len(items))
            mid = (len(items) + 1) // 2 if items else 0
            S.slide_approvals(prs, p["pss"], items, done, total, 0, mid,
                              "page 1 of 2")
            S.slide_approvals(prs, p["pss"], items, done, total, mid,
                              len(items), "page 2 of 2")

    # Phase-1 units appear in the portfolio pack only
    if not single:
        for legacy in ("PSS-10A", "PSS-05A", "PSS-08A"):
            S._unavailable(
                prs, f"Physical Progress : {legacy} S-Curve", "Phase-1 BESS",
                f"No P6 schedule exists for {legacy} in the connected systems.",
                "Pulse holds inspection records for this unit, but without a "
                "schedule there is no plan or actual to curve.")

    S._thank_you(prs)


# ── Entry points ───────────────────────────────────────────────────────────
def build_project_pptx(d: Dict[str, Any]) -> bytes:
    """One project's pack. Same slides, fewer of them."""
    meta = d["meta"]
    decl = meta["declared"]
    plan = sum(b.get("planToDatePct") or 0.0 for b in d["progress"]["buckets"])

    project = {
        "projectId": meta.get("p6Name"),
        "pss": meta["pss"], "spv": meta["spv"], "plot": meta["plot"],
        "powerMw": decl["powerMw"], "energyMwh": decl["energyMwh"],
        "dispatchableMwh": decl["dispatchableMwh"],
        "containers": decl["containers"], "landAcres": decl["landAcres"],
        "batteryOem": decl["batteryOem"],
        "planToDatePct": plan,
        "actualPct": d["progress"]["totalEarnedPct"] or 0.0,
        "buckets": d["progress"]["buckets"],
        "sCurve": d["sCurve"]["series"],
        "packages": d["procurement"]["packages"],
        "servicePackages": d["procurement"].get("servicePackages") or [],
        "sap": d["procurement"]["sap"],
        "sapNote": d["procurement"].get("sapNote"),
        "approvals": d["approvals"]["items"],
        "approvalsDone": d["approvals"]["completed"],
        "approvalsTotal": d["approvals"]["total"],
        "orderCr": d["commercial"]["orderCr"],
        "deliveredCr": d["commercial"]["deliveredCr"],
        "sapAvailable": d["procurement"]["sapAvailable"],
        "contractors": d["contractors"]["items"],
        "contractorNote": d["contractors"]["note"],
        "engineering": d.get("engineering") or {},
        "construction": d.get("construction") or {},
        "electrical": d.get("electrical") or {},
        "commissioning": d.get("commissioning") or {},
        "quality": d.get("quality") or {},
    }
    scope_meta = {
        "powerMw": decl["powerMw"], "energyMwh": decl["energyMwh"],
        "dispatchableMwh": decl["dispatchableMwh"],
        "containers": decl["containers"],
        "lastActualMonth": d["sCurve"].get("lastActualMonth"),
        "declaredSource": decl["source"],
    }
    prs = _deck()
    _compose(prs, [project], scope_meta, d["commercial"], d["manpower"],
             d.get("financial") or {}, single=True)
    buf = BytesIO()
    prs.save(buf)
    return buf.getvalue()


def build_portfolio_pptx(d: Dict[str, Any]) -> bytes:
    """All six projects, the pack's full running order."""
    prs = _deck()
    _compose(prs, d["projects"], d["meta"], d["commercial"], d["manpower"],
             d.get("financial") or {}, single=False)
    buf = BytesIO()
    prs.save(buf)
    return buf.getvalue()
