"""
Akasha Intelligence Engine — Action & Follow-up Generator

Takes insights from all domain analyzers and generates:
- Prioritized, structured action items
- Role-based assignment recommendations
- Due date suggestions
- Escalation triggers

Read-only: never modifies existing data.
"""

import logging
from datetime import datetime, timedelta

logger = logging.getLogger(__name__)

# Priority → SLA mapping (days to resolve)
PRIORITY_SLA = {
    "P1": 3,   # 3 days
    "P2": 7,   # 1 week
    "P3": 14,  # 2 weeks
    "P4": 30,  # 1 month
}

# Role hierarchy for escalation
ESCALATION_PATH = {
    "site_pm": "project_head",
    "project_head": "pmag",
    "pmag": "vp_projects",
    "procurement_head": "vp_supply_chain",
    "tc_head": "vp_transmission",
    "quality_head": "project_head",
    "finance": "cfo",
}


def generate_actions(insights: list, ctx: dict) -> list:
    """
    Generate structured action items from intelligence insights.
    Each action has: what, who, when, priority, escalation path.
    """
    now = datetime.utcnow()
    project_name = ctx["project_name"]
    actions = []

    # Collect all next_steps from insights (already generated by domain analyzers)
    # and enrich them with due dates, escalation, and tracking metadata
    seen_actions = set()

    for insight in insights:
        severity = insight.get("severity", "info")
        domain = insight.get("domain", "general")
        title = insight.get("title", "")

        # Map severity to default priority
        priority_map = {
            "critical": "P1",
            "high": "P2",
            "medium": "P3",
            "low": "P4",
            "info": "P4",
        }
        default_priority = priority_map.get(severity, "P3")

        # Generate action from insight if it's actionable
        if severity in ("critical", "high"):
            action_key = f"{domain}:{title[:50]}"
            if action_key in seen_actions:
                continue
            seen_actions.add(action_key)

            # Determine assigned role based on domain
            domain_role_map = {
                "schedule": "site_pm",
                "material": "procurement_head",
                "transmission": "tc_head",
                "financial": "finance",
                "quality": "quality_head",
                "risk": "pmag",
                "portfolio": "pmag",
            }
            assigned_role = domain_role_map.get(domain, "pmag")

            sla_days = PRIORITY_SLA.get(default_priority, 7)
            due_date = now + timedelta(days=sla_days)
            escalation_date = due_date + timedelta(days=2)  # 2 days after SLA
            escalate_to = ESCALATION_PATH.get(assigned_role, "pmag")

            actions.append({
                "title": f"[{domain.upper()}] {title}",
                "description": insight.get("description", ""),
                "priority": default_priority,
                "category": domain,
                "assigned_role": assigned_role,
                "due_date": due_date.isoformat(),
                "escalation_date": escalation_date.isoformat(),
                "escalate_to": escalate_to,
                "status": "open",
                "source_insight": title,
                "project": project_name,
                "impact": insight.get("impact", ""),
            })

    # Sort by priority (P1 first)
    actions.sort(key=lambda x: x["priority"])

    return actions
