"""Add Auth Table

Revision ID: 2c725226c403
Revises: e1d55a3b595b
Create Date: 2026-06-22 16:42:16.250920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c725226c403'
down_revision: Union[str, Sequence[str], None] = 'e1d55a3b595b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('akasha_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_akasha_user_id'), 'akasha_user', ['id'], unique=False)
    op.create_index(op.f('ix_akasha_user_role'), 'akasha_user', ['role'], unique=False)
    op.create_index(op.f('ix_akasha_user_username'), 'akasha_user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_akasha_user_username'), table_name='akasha_user')
    op.drop_index(op.f('ix_akasha_user_role'), table_name='akasha_user')
    op.drop_index(op.f('ix_akasha_user_id'), table_name='akasha_user')
    op.drop_table('akasha_user')
    # ### end Alembic commands ###
