"""add_intelligent_chatbot_tables

Revision ID: 398c32532a6e
Revises: b87a2c748bf5
Create Date: 2026-07-09 22:33:24.930064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '398c32532a6e'
down_revision: Union[str, Sequence[str], None] = 'b87a2c748bf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE INDEX IF NOT EXISTS ix_notification_category ON notification (category)")
    op.execute("DROP INDEX IF EXISTS ix_p6_activity_master_project_id")
    op.execute("CREATE INDEX IF NOT EXISTS ix_p6_activity_project_object_id ON p6_activity (project_object_id)")
    try:
        op.create_foreign_key(None, 'p6_activity', 'p6_project', ['project_object_id'], ['p6_object_id'])
    except Exception:
        pass
    
    op.execute("ALTER TABLE p6_activity DROP COLUMN IF EXISTS is_longest_path")
    op.execute("ALTER TABLE p6_activity DROP COLUMN IF EXISTS master_project_id")
    op.execute("ALTER TABLE p6_activity DROP COLUMN IF EXISTS free_float")
    op.execute("DROP INDEX IF EXISTS ix_p6_baseline_project_master_project_id")
    op.execute("CREATE INDEX IF NOT EXISTS ix_p6_baseline_project_original_project_object_id ON p6_baseline_project (original_project_object_id)")
    
    try:
        op.create_foreign_key(None, 'p6_baseline_project', 'p6_project', ['original_project_object_id'], ['p6_object_id'])
    except Exception:
        pass
    
    op.execute("ALTER TABLE p6_baseline_project DROP COLUMN IF EXISTS master_project_id")
    op.alter_column('project_mapping', 'tc_progress',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_mapping', 'tc_progress',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.add_column('p6_baseline_project', sa.Column('master_project_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'p6_baseline_project', type_='foreignkey')
    op.drop_index(op.f('ix_p6_baseline_project_original_project_object_id'), table_name='p6_baseline_project')
    op.create_index('ix_p6_baseline_project_master_project_id', 'p6_baseline_project', ['master_project_id'], unique=False)
    op.add_column('p6_activity', sa.Column('free_float', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('p6_activity', sa.Column('master_project_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('p6_activity', sa.Column('is_longest_path', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'p6_activity', type_='foreignkey')
    op.drop_index(op.f('ix_p6_activity_project_object_id'), table_name='p6_activity')
    op.create_index('ix_p6_activity_master_project_id', 'p6_activity', ['master_project_id'], unique=False)
    op.drop_index(op.f('ix_notification_category'), table_name='notification')
    # ### end Alembic commands ###
