"""Add MTMaterialDocument, P6WBSNode, and missing SAP columns

Revision ID: 548dd5ce4885
Revises: bca5adbe6e11
Create Date: 2026-06-10 11:52:08.633835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '548dd5ce4885'
down_revision: Union[str, Sequence[str], None] = 'bca5adbe6e11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('p6_wbs_node',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('p6_object_id', sa.BigInteger(), nullable=False),
    sa.Column('project_object_id', sa.BigInteger(), nullable=False),
    sa.Column('wbs_code', sa.String(), nullable=True),
    sa.Column('wbs_name', sa.String(), nullable=True),
    sa.Column('parent_object_id', sa.BigInteger(), nullable=True),
    sa.Column('is_block', sa.Boolean(), nullable=True),
    sa.Column('block_number', sa.Integer(), nullable=True),
    sa.Column('upload_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_p6_wbs_node_id'), 'p6_wbs_node', ['id'], unique=False)
    op.create_index(op.f('ix_p6_wbs_node_p6_object_id'), 'p6_wbs_node', ['p6_object_id'], unique=True)
    op.create_index(op.f('ix_p6_wbs_node_parent_object_id'), 'p6_wbs_node', ['parent_object_id'], unique=False)
    op.create_index(op.f('ix_p6_wbs_node_project_object_id'), 'p6_wbs_node', ['project_object_id'], unique=False)
    op.add_column('mt_intransit', sa.Column('grn_quantity', sa.Float(), nullable=True))
    op.add_column('mt_intransit', sa.Column('ibd_creation_date', sa.DateTime(), nullable=True))
    op.add_column('mt_intransit', sa.Column('po_quantity', sa.Float(), nullable=True))
    op.add_column('mt_intransit', sa.Column('rejected_quantity', sa.Float(), nullable=True))
    op.add_column('mt_inventory', sa.Column('special_stock', sa.String(), nullable=True))
    op.add_column('mt_inventory', sa.Column('material_type', sa.String(), nullable=True))
    op.add_column('mt_inventory', sa.Column('material_group', sa.String(), nullable=True))
    op.add_column('mt_inventory', sa.Column('material_description', sa.String(), nullable=True))
    op.add_column('mt_inventory', sa.Column('value_unrestricted', sa.Float(), nullable=True))
    op.add_column('mt_inventory', sa.Column('plant_name', sa.String(), nullable=True))
    op.drop_column('mt_materialdocument', 'company_code')
    op.drop_column('mt_materialdocument', 'mw_multiplication_factor')
    op.drop_column('mt_materialdocument', 'quantity_mw')
    op.add_column('mt_poamount', sa.Column('quantity_received', sa.Float(), nullable=True))
    op.add_column('mt_poamount', sa.Column('still_to_be_delivered_qty', sa.Float(), nullable=True))
    op.add_column('mt_poamount', sa.Column('delivery_date', sa.DateTime(), nullable=True))
    op.add_column('mt_poamount', sa.Column('delivery_completed_flag', sa.String(), nullable=True))
    op.add_column('mt_poamount', sa.Column('deletion_indicator', sa.String(), nullable=True))
    op.add_column('mt_poamount', sa.Column('document_date', sa.DateTime(), nullable=True))
    op.add_column('mt_poamount', sa.Column('short_text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mt_poamount', 'short_text')
    op.drop_column('mt_poamount', 'document_date')
    op.drop_column('mt_poamount', 'deletion_indicator')
    op.drop_column('mt_poamount', 'delivery_completed_flag')
    op.drop_column('mt_poamount', 'delivery_date')
    op.drop_column('mt_poamount', 'still_to_be_delivered_qty')
    op.drop_column('mt_poamount', 'quantity_received')
    op.add_column('mt_materialdocument', sa.Column('quantity_mw', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('mt_materialdocument', sa.Column('mw_multiplication_factor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('mt_materialdocument', sa.Column('company_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('mt_inventory', 'plant_name')
    op.drop_column('mt_inventory', 'value_unrestricted')
    op.drop_column('mt_inventory', 'material_description')
    op.drop_column('mt_inventory', 'material_group')
    op.drop_column('mt_inventory', 'material_type')
    op.drop_column('mt_inventory', 'special_stock')
    op.drop_column('mt_intransit', 'rejected_quantity')
    op.drop_column('mt_intransit', 'po_quantity')
    op.drop_column('mt_intransit', 'ibd_creation_date')
    op.drop_column('mt_intransit', 'grn_quantity')
    op.drop_index(op.f('ix_p6_wbs_node_project_object_id'), table_name='p6_wbs_node')
    op.drop_index(op.f('ix_p6_wbs_node_parent_object_id'), table_name='p6_wbs_node')
    op.drop_index(op.f('ix_p6_wbs_node_p6_object_id'), table_name='p6_wbs_node')
    op.drop_index(op.f('ix_p6_wbs_node_id'), table_name='p6_wbs_node')
    op.drop_table('p6_wbs_node')
    # ### end Alembic commands ###
