"""Add Mapping Keys to Master Project

Revision ID: 66dc139ec2d1
Revises: 2c725226c403
Create Date: 2026-06-22 16:49:24.458761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66dc139ec2d1'
down_revision: Union[str, Sequence[str], None] = '2c725226c403'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master_project', sa.Column('sap_plant_code', sa.String(), nullable=True))
    op.add_column('master_project', sa.Column('sap_wbs_element', sa.String(), nullable=True))
    op.add_column('master_project', sa.Column('p6_eps_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_master_project_p6_eps_name'), 'master_project', ['p6_eps_name'], unique=False)
    op.create_index(op.f('ix_master_project_sap_plant_code'), 'master_project', ['sap_plant_code'], unique=False)
    op.create_index(op.f('ix_master_project_sap_wbs_element'), 'master_project', ['sap_wbs_element'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_master_project_sap_wbs_element'), table_name='master_project')
    op.drop_index(op.f('ix_master_project_sap_plant_code'), table_name='master_project')
    op.drop_index(op.f('ix_master_project_p6_eps_name'), table_name='master_project')
    op.drop_column('master_project', 'p6_eps_name')
    op.drop_column('master_project', 'sap_wbs_element')
    op.drop_column('master_project', 'sap_plant_code')
    # ### end Alembic commands ###
