"""Add storage_location_desc to MTInventory

Revision ID: 6789335f61d7
Revises: 548dd5ce4885
Create Date: 2026-06-14 02:09:22.831881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6789335f61d7'
down_revision: Union[str, Sequence[str], None] = '548dd5ce4885'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mt_inventory', sa.Column('storage_location_desc', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mt_inventory', 'storage_location_desc')
    # ### end Alembic commands ###
