"""Add P6CapacityMilestone

Revision ID: 71a6d9b3c1b6
Revises: 66dc139ec2d1
Create Date: 2026-06-22 16:55:39.486779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '71a6d9b3c1b6'
down_revision: Union[str, Sequence[str], None] = '66dc139ec2d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('p6_capacity_milestone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_project_id', sa.Integer(), nullable=True),
    sa.Column('activity_id', sa.String(), nullable=True),
    sa.Column('activity_name', sa.String(), nullable=True),
    sa.Column('block_name', sa.String(), nullable=True),
    sa.Column('unit_of_measure', sa.String(), nullable=True),
    sa.Column('capacity_mw', sa.Float(), nullable=True),
    sa.Column('milestone_type', sa.String(), nullable=True),
    sa.Column('actual_start_date', sa.DateTime(), nullable=True),
    sa.Column('actual_finish_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['master_project_id'], ['master_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_p6_capacity_milestone_activity_id'), 'p6_capacity_milestone', ['activity_id'], unique=True)
    op.create_index(op.f('ix_p6_capacity_milestone_id'), 'p6_capacity_milestone', ['id'], unique=False)
    op.create_index(op.f('ix_p6_capacity_milestone_master_project_id'), 'p6_capacity_milestone', ['master_project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('p6_baseline_project', sa.Column('completed_activity_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('p6_baseline_project', sa.Column('planned_duration', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('p6_baseline_project', sa.Column('last_synced_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('p6_baseline_project', sa.Column('activity_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('p6_baseline_project', sa.Column('not_started_activity_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('p6_baseline_project', sa.Column('remaining_total_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('p6_baseline_project', sa.Column('original_budget', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('p6_baseline_project', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('p6_baseline_project', sa.Column('baseline_total_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('p6_baseline_project', sa.Column('scheduled_finish_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('p6_baseline_project', sa.Column('actual_total_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('p6_baseline_project', sa.Column('actual_duration', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('p6_baseline_project', sa.Column('original_project_object_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('p6_baseline_project', sa.Column('remaining_duration', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('p6_baseline_project', sa.Column('planned_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('p6_baseline_project', sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('p6_baseline_project', sa.Column('in_progress_activity_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('p6_baseline_project', sa.Column('current_budget', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('p6_activity', sa.Column('baseline_start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('p6_activity', sa.Column('baseline_finish_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('p6_activity', sa.Column('project_object_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_table('mt_trialrun',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('activity_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('project_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('project_name_block', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('trial_run_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('trial_run_finish', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('activity_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tr_quantity_mw', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('unit_of_measure', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('project_name_p6', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('spv_plant_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_start_before_upload', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('upload_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('mt_trialrun_pkey'))
    )
    op.create_index(op.f('ix_mt_trialrun_spv_plant_code'), 'mt_trialrun', ['spv_plant_code'], unique=False)
    op.create_index(op.f('ix_mt_trialrun_id'), 'mt_trialrun', ['id'], unique=False)
    op.create_index(op.f('ix_mt_trialrun_activity_id'), 'mt_trialrun', ['activity_id'], unique=True)
    op.create_table('mt_underconstruction',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('plant_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('material_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('quantity_uc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('vendor_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('posting_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('purchase_order', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('storage_location_mapping', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('movement_type_validation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mw_multiplication_factor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('quantity_mw', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('upload_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('mt_underconstruction_pkey'))
    )
    op.create_index(op.f('ix_mt_underconstruction_plant_code'), 'mt_underconstruction', ['plant_code'], unique=False)
    op.create_index(op.f('ix_mt_underconstruction_id'), 'mt_underconstruction', ['id'], unique=False)
    op.create_table('p6_wbs_node',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('p6_object_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('project_object_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('wbs_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('wbs_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('parent_object_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('is_block', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('block_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('upload_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('p6_wbs_node_pkey'))
    )
    op.create_index(op.f('ix_p6_wbs_node_project_object_id'), 'p6_wbs_node', ['project_object_id'], unique=False)
    op.create_index(op.f('ix_p6_wbs_node_parent_object_id'), 'p6_wbs_node', ['parent_object_id'], unique=False)
    op.create_index(op.f('ix_p6_wbs_node_p6_object_id'), 'p6_wbs_node', ['p6_object_id'], unique=True)
    op.create_index(op.f('ix_p6_wbs_node_id'), 'p6_wbs_node', ['id'], unique=False)
    op.create_table('tc_network_node',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('region', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('node_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('label', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('x', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('y', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('upload_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('tc_network_node_pkey'))
    )
    op.create_index(op.f('ix_tc_network_node_region'), 'tc_network_node', ['region'], unique=False)
    op.create_index(op.f('ix_tc_network_node_node_id'), 'tc_network_node', ['node_id'], unique=False)
    op.create_index(op.f('ix_tc_network_node_id'), 'tc_network_node', ['id'], unique=False)
    op.create_table('mt_requirement',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('activity_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('project_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('block', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('activity_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('budgeted_units_mw', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('unit_of_measure', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('project_name_p6', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('spv_plant_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source_of_origin', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('upload_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('mt_requirement_pkey'))
    )
    op.create_index(op.f('ix_mt_requirement_spv_plant_code'), 'mt_requirement', ['spv_plant_code'], unique=False)
    op.create_index(op.f('ix_mt_requirement_project_name'), 'mt_requirement', ['project_name'], unique=False)
    op.create_index(op.f('ix_mt_requirement_id'), 'mt_requirement', ['id'], unique=False)
    op.create_index(op.f('ix_mt_requirement_activity_name'), 'mt_requirement', ['activity_name'], unique=False)
    op.create_index(op.f('ix_mt_requirement_activity_id'), 'mt_requirement', ['activity_id'], unique=True)
    op.create_table('mt_materialdocument',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('material_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('plant_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('movement_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('posting_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('material_document', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('wbs_element', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('material_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('material_description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('amount_in_lc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('amount_in_lc_cr', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('storage_location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('block_plot_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('purchase_order', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('base_unit', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('upload_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('mt_materialdocument_pkey'))
    )
    op.create_index(op.f('ix_mt_materialdocument_wbs_element'), 'mt_materialdocument', ['wbs_element'], unique=False)
    op.create_index(op.f('ix_mt_materialdocument_plant_code'), 'mt_materialdocument', ['plant_code'], unique=False)
    op.create_index(op.f('ix_mt_materialdocument_material_code'), 'mt_materialdocument', ['material_code'], unique=False)
    op.create_index(op.f('ix_mt_materialdocument_id'), 'mt_materialdocument', ['id'], unique=False)
    op.create_table('tc_network_edge',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('region', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('edge_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('from_node', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('from_label', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('to_node', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('to_label', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('projects', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('contractor', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('voltage', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('length', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('normalized_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('erection', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('foundation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('stringing', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('expected_date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mapping_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('upload_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['mapping_id'], ['project_mapping.id'], name=op.f('tc_network_edge_mapping_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tc_network_edge_pkey'))
    )
    op.create_index(op.f('ix_tc_network_edge_region'), 'tc_network_edge', ['region'], unique=False)
    op.create_index(op.f('ix_tc_network_edge_id'), 'tc_network_edge', ['id'], unique=False)
    op.create_index(op.f('ix_tc_network_edge_edge_id'), 'tc_network_edge', ['edge_id'], unique=False)
    op.create_table('p6_project',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('p6_object_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('finish_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('planned_start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('scheduled_finish_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('data_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('must_finish_by_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('duration_percent_complete', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('planned_duration', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('actual_duration', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('remaining_duration', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('activity_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('completed_activity_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('in_progress_activity_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('not_started_activity_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_float', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('finish_date_variance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('start_date_variance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('duration_variance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('actual_total_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('planned_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cost_performance_index', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('schedule_performance_index', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('current_budget', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_cost_variance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('location_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('parent_eps_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('current_baseline_project_object_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('baseline_start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('baseline_finish_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('baseline_duration', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('baseline_total_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('baseline_completed_activity_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('baseline_in_progress_activity_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('baseline_not_started_activity_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_synced_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('p6_project_pkey'))
    )
    op.create_index(op.f('ix_p6_project_status'), 'p6_project', ['status'], unique=False)
    op.create_index(op.f('ix_p6_project_project_id'), 'p6_project', ['project_id'], unique=False)
    op.create_index(op.f('ix_p6_project_p6_object_id'), 'p6_project', ['p6_object_id'], unique=True)
    op.create_index(op.f('ix_p6_project_name'), 'p6_project', ['name'], unique=False)
    op.create_index(op.f('ix_p6_project_id'), 'p6_project', ['id'], unique=False)
    op.create_table('mt_intransit',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('material_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('inbound_delivery_quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('company_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('plant_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('gr_posting_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('ariba_invoice_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('vendor_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('vendor_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('po_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('wbs_element', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mw_multiplication_factor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('quantity_mw', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('grn_quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ibd_creation_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('po_quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('rejected_quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('upload_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('mt_intransit_pkey'))
    )
    op.create_index(op.f('ix_mt_intransit_wbs_element'), 'mt_intransit', ['wbs_element'], unique=False)
    op.create_index(op.f('ix_mt_intransit_plant_code'), 'mt_intransit', ['plant_code'], unique=False)
    op.create_index(op.f('ix_mt_intransit_material_code'), 'mt_intransit', ['material_code'], unique=False)
    op.create_index(op.f('ix_mt_intransit_id'), 'mt_intransit', ['id'], unique=False)
    op.create_table('tc_project_entry',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('region', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('project', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phase', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('kps', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pss', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('block', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('breakup', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mw', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('mapping_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('upload_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['mapping_id'], ['project_mapping.id'], name=op.f('tc_project_entry_mapping_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tc_project_entry_pkey'))
    )
    op.create_index(op.f('ix_tc_project_entry_region'), 'tc_project_entry', ['region'], unique=False)
    op.create_index(op.f('ix_tc_project_entry_project'), 'tc_project_entry', ['project'], unique=False)
    op.create_index(op.f('ix_tc_project_entry_id'), 'tc_project_entry', ['id'], unique=False)
    op.create_table('mt_poamount',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('plant_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('purchasing_document', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('wbs_element', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('material_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('vendor_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('vendor_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('po_quantities', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('material_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mw_multiplication_factor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('po_quantities_mw', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('net_order_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('quantity_received', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('still_to_be_delivered_qty', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('delivery_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('delivery_completed_flag', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('deletion_indicator', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('document_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('short_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('material_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('order_quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('net_order_value_inr', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('still_to_deliver_qty', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('still_to_deliver_inr', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('delivered_qty', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('delivered_value_inr_cr', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('storage_location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('block_plot_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('upload_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('mt_poamount_pkey'))
    )
    op.create_index(op.f('ix_mt_poamount_wbs_element'), 'mt_poamount', ['wbs_element'], unique=False)
    op.create_index(op.f('ix_mt_poamount_purchasing_document'), 'mt_poamount', ['purchasing_document'], unique=False)
    op.create_index(op.f('ix_mt_poamount_plant_code'), 'mt_poamount', ['plant_code'], unique=False)
    op.create_index(op.f('ix_mt_poamount_id'), 'mt_poamount', ['id'], unique=False)
    op.create_table('mt_inventory',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('plant_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('material_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('quantity_inv', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('vendor_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('posting_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('purchase_order', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('wbs_element', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('storage_location_mapping', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('movement_type_validation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mw_multiplication_factor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('quantity_mw', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('special_stock', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('material_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('material_group', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('material_description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('value_unrestricted', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('plant_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('material_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('unrestricted_qty', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('upload_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('mt_inventory_pkey'))
    )
    op.create_index(op.f('ix_mt_inventory_wbs_element'), 'mt_inventory', ['wbs_element'], unique=False)
    op.create_index(op.f('ix_mt_inventory_plant_code'), 'mt_inventory', ['plant_code'], unique=False)
    op.create_index(op.f('ix_mt_inventory_id'), 'mt_inventory', ['id'], unique=False)
    op.create_table('project_mapping',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('spv_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('project_name_from_p6', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('plot_no', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mms_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('capacity_mwac', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ol', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('capacity_mwdc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('spv_plant_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('agel', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('module_wbs', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('age6l', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cluster', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('not_allocated', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source_of_origin', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('project_mapping_pkey'))
    )
    op.create_index(op.f('ix_project_mapping_spv_plant_code'), 'project_mapping', ['spv_plant_code'], unique=False)
    op.create_index(op.f('ix_project_mapping_project_id'), 'project_mapping', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_mapping_project'), 'project_mapping', ['project'], unique=False)
    op.create_index(op.f('ix_project_mapping_module_wbs'), 'project_mapping', ['module_wbs'], unique=False)
    op.create_index(op.f('ix_project_mapping_id'), 'project_mapping', ['id'], unique=False)
    # ### end Alembic commands ###
