"""Add MTMaterialDocument

Revision ID: bca5adbe6e11
Revises: ea078dca8c34
Create Date: 2026-06-10 09:19:33.429270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bca5adbe6e11'
down_revision: Union[str, Sequence[str], None] = 'ea078dca8c34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mt_materialdocument',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_code', sa.String(), nullable=True),
    sa.Column('plant_code', sa.String(), nullable=True),
    sa.Column('material_code', sa.String(), nullable=True),
    sa.Column('movement_type', sa.String(), nullable=True),
    sa.Column('posting_date', sa.DateTime(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('material_document', sa.String(), nullable=True),
    sa.Column('wbs_element', sa.String(), nullable=True),
    sa.Column('mw_multiplication_factor', sa.Float(), nullable=True),
    sa.Column('quantity_mw', sa.Float(), nullable=True),
    sa.Column('upload_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mt_materialdocument_id'), 'mt_materialdocument', ['id'], unique=False)
    op.create_index(op.f('ix_mt_materialdocument_material_code'), 'mt_materialdocument', ['material_code'], unique=False)
    op.create_index(op.f('ix_mt_materialdocument_plant_code'), 'mt_materialdocument', ['plant_code'], unique=False)
    op.create_index(op.f('ix_mt_materialdocument_wbs_element'), 'mt_materialdocument', ['wbs_element'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mt_materialdocument_wbs_element'), table_name='mt_materialdocument')
    op.drop_index(op.f('ix_mt_materialdocument_plant_code'), table_name='mt_materialdocument')
    op.drop_index(op.f('ix_mt_materialdocument_material_code'), table_name='mt_materialdocument')
    op.drop_index(op.f('ix_mt_materialdocument_id'), table_name='mt_materialdocument')
    op.drop_table('mt_materialdocument')
    # ### end Alembic commands ###
