"""Add missing columns

Revision ID: e036d945b869
Revises: 6789335f61d7
Create Date: 2026-06-17 15:34:19.961759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e036d945b869'
down_revision: Union[str, Sequence[str], None] = '6789335f61d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mt_inventory', 'storage_location_desc')
    op.drop_column('mt_poamount', 'order_unit')
    op.drop_column('mt_poamount', 'delivered_value_cr')
    op.drop_column('mt_poamount', 'validity_start')
    op.drop_column('mt_poamount', 'net_price')
    op.drop_column('mt_poamount', 'validity_end')
    op.drop_column('mt_poamount', 'still_to_be_delivered_value_inr')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mt_poamount', sa.Column('still_to_be_delivered_value_inr', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('mt_poamount', sa.Column('validity_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('mt_poamount', sa.Column('net_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('mt_poamount', sa.Column('validity_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('mt_poamount', sa.Column('delivered_value_cr', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('mt_poamount', sa.Column('order_unit', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mt_inventory', sa.Column('storage_location_desc', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
