"""Initial Master-Child Schema

Revision ID: e1d55a3b595b
Revises: 
Create Date: 2026-06-22 16:41:22.121711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1d55a3b595b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=True),
    sa.Column('spv_name', sa.String(), nullable=True),
    sa.Column('capacity_mwac', sa.Float(), nullable=True),
    sa.Column('capacity_mwdc', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('planned_progress', sa.Float(), nullable=True),
    sa.Column('actual_progress', sa.Float(), nullable=True),
    sa.Column('cpi', sa.Float(), nullable=True),
    sa.Column('spi', sa.Float(), nullable=True),
    sa.Column('critical_path_delay_days', sa.Integer(), nullable=True),
    sa.Column('total_material_budget', sa.Float(), nullable=True),
    sa.Column('actual_material_cost', sa.Float(), nullable=True),
    sa.Column('materials_in_transit_mw', sa.Float(), nullable=True),
    sa.Column('transmission_readiness_status', sa.String(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_project_id'), 'master_project', ['id'], unique=False)
    op.create_index(op.f('ix_master_project_project_id'), 'master_project', ['project_id'], unique=True)
    op.create_index(op.f('ix_master_project_project_name'), 'master_project', ['project_name'], unique=False)
    op.create_table('sap_material_dimension',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_code', sa.String(), nullable=True),
    sa.Column('material_name', sa.String(), nullable=True),
    sa.Column('material_description', sa.String(), nullable=True),
    sa.Column('material_type', sa.String(), nullable=True),
    sa.Column('material_group', sa.String(), nullable=True),
    sa.Column('base_unit', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sap_material_dimension_id'), 'sap_material_dimension', ['id'], unique=False)
    op.create_index(op.f('ix_sap_material_dimension_material_code'), 'sap_material_dimension', ['material_code'], unique=True)
    op.create_table('sap_vendor_dimension',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_code', sa.String(), nullable=True),
    sa.Column('vendor_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sap_vendor_dimension_id'), 'sap_vendor_dimension', ['id'], unique=False)
    op.create_index(op.f('ix_sap_vendor_dimension_vendor_code'), 'sap_vendor_dimension', ['vendor_code'], unique=True)
    op.create_table('p6_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('p6_object_id', sa.BigInteger(), nullable=False),
    sa.Column('master_project_id', sa.Integer(), nullable=True),
    sa.Column('activity_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('finish_date', sa.DateTime(), nullable=True),
    sa.Column('planned_start_date', sa.DateTime(), nullable=True),
    sa.Column('planned_finish_date', sa.DateTime(), nullable=True),
    sa.Column('actual_start_date', sa.DateTime(), nullable=True),
    sa.Column('actual_finish_date', sa.DateTime(), nullable=True),
    sa.Column('planned_duration', sa.Float(), nullable=True),
    sa.Column('actual_duration', sa.Float(), nullable=True),
    sa.Column('remaining_duration', sa.Float(), nullable=True),
    sa.Column('percent_complete', sa.Float(), nullable=True),
    sa.Column('total_float', sa.Float(), nullable=True),
    sa.Column('free_float', sa.Float(), nullable=True),
    sa.Column('is_critical', sa.Boolean(), nullable=True),
    sa.Column('is_longest_path', sa.Boolean(), nullable=True),
    sa.Column('wbs_object_id', sa.BigInteger(), nullable=True),
    sa.Column('wbs_name', sa.String(), nullable=True),
    sa.Column('wbs_code', sa.String(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['master_project_id'], ['master_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_p6_activity_activity_id'), 'p6_activity', ['activity_id'], unique=False)
    op.create_index(op.f('ix_p6_activity_id'), 'p6_activity', ['id'], unique=False)
    op.create_index(op.f('ix_p6_activity_master_project_id'), 'p6_activity', ['master_project_id'], unique=False)
    op.create_index(op.f('ix_p6_activity_p6_object_id'), 'p6_activity', ['p6_object_id'], unique=True)
    op.create_table('p6_baseline_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('p6_object_id', sa.BigInteger(), nullable=False),
    sa.Column('master_project_id', sa.Integer(), nullable=True),
    sa.Column('baseline_type_name', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('planned_start_date', sa.DateTime(), nullable=True),
    sa.Column('finish_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['master_project_id'], ['master_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_p6_baseline_project_id'), 'p6_baseline_project', ['id'], unique=False)
    op.create_index(op.f('ix_p6_baseline_project_master_project_id'), 'p6_baseline_project', ['master_project_id'], unique=False)
    op.create_index(op.f('ix_p6_baseline_project_p6_object_id'), 'p6_baseline_project', ['p6_object_id'], unique=True)
    op.create_table('p6_project_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_project_id', sa.Integer(), nullable=True),
    sa.Column('p6_object_id', sa.BigInteger(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('finish_date', sa.DateTime(), nullable=True),
    sa.Column('planned_start_date', sa.DateTime(), nullable=True),
    sa.Column('scheduled_finish_date', sa.DateTime(), nullable=True),
    sa.Column('must_finish_by_date', sa.DateTime(), nullable=True),
    sa.Column('data_date', sa.DateTime(), nullable=True),
    sa.Column('planned_duration', sa.Float(), nullable=True),
    sa.Column('actual_duration', sa.Float(), nullable=True),
    sa.Column('remaining_duration', sa.Float(), nullable=True),
    sa.Column('activity_count', sa.Integer(), nullable=True),
    sa.Column('completed_activity_count', sa.Integer(), nullable=True),
    sa.Column('in_progress_activity_count', sa.Integer(), nullable=True),
    sa.Column('not_started_activity_count', sa.Integer(), nullable=True),
    sa.Column('total_float', sa.Float(), nullable=True),
    sa.Column('finish_date_variance', sa.Float(), nullable=True),
    sa.Column('actual_total_cost', sa.Float(), nullable=True),
    sa.Column('planned_cost', sa.Float(), nullable=True),
    sa.Column('current_budget', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['master_project_id'], ['master_project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('master_project_id')
    )
    op.create_index(op.f('ix_p6_project_details_id'), 'p6_project_details', ['id'], unique=False)
    op.create_index(op.f('ix_p6_project_details_p6_object_id'), 'p6_project_details', ['p6_object_id'], unique=True)
    op.create_table('sap_inventory_balance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_project_id', sa.Integer(), nullable=True),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('plant_code', sa.String(), nullable=True),
    sa.Column('storage_location', sa.String(), nullable=True),
    sa.Column('unrestricted_qty', sa.Float(), nullable=True),
    sa.Column('quantity_mw', sa.Float(), nullable=True),
    sa.Column('value_unrestricted', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['master_project_id'], ['master_project.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['sap_material_dimension.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sap_inventory_balance_id'), 'sap_inventory_balance', ['id'], unique=False)
    op.create_index(op.f('ix_sap_inventory_balance_master_project_id'), 'sap_inventory_balance', ['master_project_id'], unique=False)
    op.create_index(op.f('ix_sap_inventory_balance_plant_code'), 'sap_inventory_balance', ['plant_code'], unique=False)
    op.create_table('sap_material_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_project_id', sa.Integer(), nullable=True),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('po_number', sa.String(), nullable=True),
    sa.Column('plant_code', sa.String(), nullable=True),
    sa.Column('wbs_element', sa.String(), nullable=True),
    sa.Column('transaction_type', sa.String(), nullable=True),
    sa.Column('posting_date', sa.DateTime(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('quantity_mw', sa.Float(), nullable=True),
    sa.Column('net_value', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['master_project_id'], ['master_project.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['sap_material_dimension.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['sap_vendor_dimension.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sap_material_transaction_id'), 'sap_material_transaction', ['id'], unique=False)
    op.create_index(op.f('ix_sap_material_transaction_master_project_id'), 'sap_material_transaction', ['master_project_id'], unique=False)
    op.create_index(op.f('ix_sap_material_transaction_plant_code'), 'sap_material_transaction', ['plant_code'], unique=False)
    op.create_index(op.f('ix_sap_material_transaction_po_number'), 'sap_material_transaction', ['po_number'], unique=False)
    op.create_index(op.f('ix_sap_material_transaction_wbs_element'), 'sap_material_transaction', ['wbs_element'], unique=False)
    op.create_table('transmission_edge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_project_id', sa.Integer(), nullable=True),
    sa.Column('edge_id', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('from_node', sa.String(), nullable=True),
    sa.Column('to_node', sa.String(), nullable=True),
    sa.Column('contractor', sa.String(), nullable=True),
    sa.Column('voltage', sa.String(), nullable=True),
    sa.Column('length', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('erection_status', sa.String(), nullable=True),
    sa.Column('foundation_status', sa.String(), nullable=True),
    sa.Column('stringing_status', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['master_project_id'], ['master_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transmission_edge_edge_id'), 'transmission_edge', ['edge_id'], unique=False)
    op.create_index(op.f('ix_transmission_edge_id'), 'transmission_edge', ['id'], unique=False)
    op.create_index(op.f('ix_transmission_edge_master_project_id'), 'transmission_edge', ['master_project_id'], unique=False)
    op.create_table('transmission_node',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_project_id', sa.Integer(), nullable=True),
    sa.Column('node_id', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('x_coordinate', sa.Float(), nullable=True),
    sa.Column('y_coordinate', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['master_project_id'], ['master_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transmission_node_id'), 'transmission_node', ['id'], unique=False)
    op.create_index(op.f('ix_transmission_node_master_project_id'), 'transmission_node', ['master_project_id'], unique=False)
    op.create_index(op.f('ix_transmission_node_node_id'), 'transmission_node', ['node_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transmission_node_node_id'), table_name='transmission_node')
    op.drop_index(op.f('ix_transmission_node_master_project_id'), table_name='transmission_node')
    op.drop_index(op.f('ix_transmission_node_id'), table_name='transmission_node')
    op.drop_table('transmission_node')
    op.drop_index(op.f('ix_transmission_edge_master_project_id'), table_name='transmission_edge')
    op.drop_index(op.f('ix_transmission_edge_id'), table_name='transmission_edge')
    op.drop_index(op.f('ix_transmission_edge_edge_id'), table_name='transmission_edge')
    op.drop_table('transmission_edge')
    op.drop_index(op.f('ix_sap_material_transaction_wbs_element'), table_name='sap_material_transaction')
    op.drop_index(op.f('ix_sap_material_transaction_po_number'), table_name='sap_material_transaction')
    op.drop_index(op.f('ix_sap_material_transaction_plant_code'), table_name='sap_material_transaction')
    op.drop_index(op.f('ix_sap_material_transaction_master_project_id'), table_name='sap_material_transaction')
    op.drop_index(op.f('ix_sap_material_transaction_id'), table_name='sap_material_transaction')
    op.drop_table('sap_material_transaction')
    op.drop_index(op.f('ix_sap_inventory_balance_plant_code'), table_name='sap_inventory_balance')
    op.drop_index(op.f('ix_sap_inventory_balance_master_project_id'), table_name='sap_inventory_balance')
    op.drop_index(op.f('ix_sap_inventory_balance_id'), table_name='sap_inventory_balance')
    op.drop_table('sap_inventory_balance')
    op.drop_index(op.f('ix_p6_project_details_p6_object_id'), table_name='p6_project_details')
    op.drop_index(op.f('ix_p6_project_details_id'), table_name='p6_project_details')
    op.drop_table('p6_project_details')
    op.drop_index(op.f('ix_p6_baseline_project_p6_object_id'), table_name='p6_baseline_project')
    op.drop_index(op.f('ix_p6_baseline_project_master_project_id'), table_name='p6_baseline_project')
    op.drop_index(op.f('ix_p6_baseline_project_id'), table_name='p6_baseline_project')
    op.drop_table('p6_baseline_project')
    op.drop_index(op.f('ix_p6_activity_p6_object_id'), table_name='p6_activity')
    op.drop_index(op.f('ix_p6_activity_master_project_id'), table_name='p6_activity')
    op.drop_index(op.f('ix_p6_activity_id'), table_name='p6_activity')
    op.drop_index(op.f('ix_p6_activity_activity_id'), table_name='p6_activity')
    op.drop_table('p6_activity')
    op.drop_index(op.f('ix_sap_vendor_dimension_vendor_code'), table_name='sap_vendor_dimension')
    op.drop_index(op.f('ix_sap_vendor_dimension_id'), table_name='sap_vendor_dimension')
    op.drop_table('sap_vendor_dimension')
    op.drop_index(op.f('ix_sap_material_dimension_material_code'), table_name='sap_material_dimension')
    op.drop_index(op.f('ix_sap_material_dimension_id'), table_name='sap_material_dimension')
    op.drop_table('sap_material_dimension')
    op.drop_index(op.f('ix_master_project_project_name'), table_name='master_project')
    op.drop_index(op.f('ix_master_project_project_id'), table_name='master_project')
    op.drop_index(op.f('ix_master_project_id'), table_name='master_project')
    op.drop_table('master_project')
    # ### end Alembic commands ###
