"""Initial migration

Revision ID: ea078dca8c34
Revises: 
Create Date: 2026-06-08 10:34:34.496820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea078dca8c34'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_mt_intransit_wbs_element'), 'mt_intransit', ['wbs_element'], unique=False)
    op.create_index(op.f('ix_mt_inventory_wbs_element'), 'mt_inventory', ['wbs_element'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mt_inventory_wbs_element'), table_name='mt_inventory')
    op.drop_index(op.f('ix_mt_intransit_wbs_element'), table_name='mt_intransit')
    # ### end Alembic commands ###
