"""Add PulseNC and PulseRFI

Revision ID: fd3a008bc83b
Revises: 398c32532a6e
Create Date: 2026-07-17 10:46:47.755190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd3a008bc83b'
down_revision: Union[str, Sequence[str], None] = '398c32532a6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pulse_nc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pulse_id', sa.String(), nullable=False),
    sa.Column('nc_label', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('status_label', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('defect_type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('ad_hoc', sa.Boolean(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('current_handler', sa.String(), nullable=True),
    sa.Column('debit', sa.Float(), nullable=True),
    sa.Column('debit_reason', sa.String(), nullable=True),
    sa.Column('cluster_name', sa.String(), nullable=True),
    sa.Column('project_name', sa.String(), nullable=True),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('project_type', sa.String(), nullable=True),
    sa.Column('spv_name', sa.String(), nullable=True),
    sa.Column('worklocation_name', sa.String(), nullable=True),
    sa.Column('workarea_name', sa.String(), nullable=True),
    sa.Column('contractor_name', sa.String(), nullable=True),
    sa.Column('vendor_name', sa.String(), nullable=True),
    sa.Column('vendor_code', sa.String(), nullable=True),
    sa.Column('engineer_name', sa.String(), nullable=True),
    sa.Column('quality_name', sa.String(), nullable=True),
    sa.Column('package_name', sa.String(), nullable=True),
    sa.Column('subpackage_name', sa.String(), nullable=True),
    sa.Column('activity_name', sa.String(), nullable=True),
    sa.Column('subactivity_name', sa.String(), nullable=True),
    sa.Column('service_order_number', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pulse_nc_category'), 'pulse_nc', ['category'], unique=False)
    op.create_index(op.f('ix_pulse_nc_cluster_name'), 'pulse_nc', ['cluster_name'], unique=False)
    op.create_index(op.f('ix_pulse_nc_current_handler'), 'pulse_nc', ['current_handler'], unique=False)
    op.create_index(op.f('ix_pulse_nc_id'), 'pulse_nc', ['id'], unique=False)
    op.create_index(op.f('ix_pulse_nc_nc_label'), 'pulse_nc', ['nc_label'], unique=False)
    op.create_index(op.f('ix_pulse_nc_package_name'), 'pulse_nc', ['package_name'], unique=False)
    op.create_index(op.f('ix_pulse_nc_project_id'), 'pulse_nc', ['project_id'], unique=False)
    op.create_index(op.f('ix_pulse_nc_project_name'), 'pulse_nc', ['project_name'], unique=False)
    op.create_index(op.f('ix_pulse_nc_pulse_id'), 'pulse_nc', ['pulse_id'], unique=True)
    op.create_index(op.f('ix_pulse_nc_status'), 'pulse_nc', ['status'], unique=False)
    op.create_index(op.f('ix_pulse_nc_vendor_name'), 'pulse_nc', ['vendor_name'], unique=False)
    op.create_table('pulse_rfi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pulse_id', sa.String(), nullable=False),
    sa.Column('rfi_label', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('status_label', sa.String(), nullable=True),
    sa.Column('current_handler', sa.String(), nullable=True),
    sa.Column('cluster_name', sa.String(), nullable=True),
    sa.Column('project_name', sa.String(), nullable=True),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('project_type', sa.String(), nullable=True),
    sa.Column('spv_name', sa.String(), nullable=True),
    sa.Column('worklocation_name', sa.String(), nullable=True),
    sa.Column('workarea_name', sa.String(), nullable=True),
    sa.Column('contractor_name', sa.String(), nullable=True),
    sa.Column('vendor_name', sa.String(), nullable=True),
    sa.Column('engineer_name', sa.String(), nullable=True),
    sa.Column('quality_name', sa.String(), nullable=True),
    sa.Column('package_name', sa.String(), nullable=True),
    sa.Column('inspection_point_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pulse_rfi_cluster_name'), 'pulse_rfi', ['cluster_name'], unique=False)
    op.create_index(op.f('ix_pulse_rfi_id'), 'pulse_rfi', ['id'], unique=False)
    op.create_index(op.f('ix_pulse_rfi_project_id'), 'pulse_rfi', ['project_id'], unique=False)
    op.create_index(op.f('ix_pulse_rfi_project_name'), 'pulse_rfi', ['project_name'], unique=False)
    op.create_index(op.f('ix_pulse_rfi_pulse_id'), 'pulse_rfi', ['pulse_id'], unique=True)
    op.create_index(op.f('ix_pulse_rfi_rfi_label'), 'pulse_rfi', ['rfi_label'], unique=False)
    op.create_index(op.f('ix_pulse_rfi_status'), 'pulse_rfi', ['status'], unique=False)
    op.create_index(op.f('ix_notification_category'), 'notification', ['category'], unique=False)
    op.create_index(op.f('ix_p6_activity_project_object_id'), 'p6_activity', ['project_object_id'], unique=False)
    op.create_index(op.f('ix_p6_baseline_project_original_project_object_id'), 'p6_baseline_project', ['original_project_object_id'], unique=False)
    op.drop_column('p6_project', 'construction_percent_complete')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('p6_project', sa.Column('construction_percent_complete', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_p6_baseline_project_original_project_object_id'), table_name='p6_baseline_project')
    op.drop_index(op.f('ix_p6_activity_project_object_id'), table_name='p6_activity')
    op.drop_index(op.f('ix_notification_category'), table_name='notification')
    op.drop_index(op.f('ix_pulse_rfi_status'), table_name='pulse_rfi')
    op.drop_index(op.f('ix_pulse_rfi_rfi_label'), table_name='pulse_rfi')
    op.drop_index(op.f('ix_pulse_rfi_pulse_id'), table_name='pulse_rfi')
    op.drop_index(op.f('ix_pulse_rfi_project_name'), table_name='pulse_rfi')
    op.drop_index(op.f('ix_pulse_rfi_project_id'), table_name='pulse_rfi')
    op.drop_index(op.f('ix_pulse_rfi_id'), table_name='pulse_rfi')
    op.drop_index(op.f('ix_pulse_rfi_cluster_name'), table_name='pulse_rfi')
    op.drop_table('pulse_rfi')
    op.drop_index(op.f('ix_pulse_nc_vendor_name'), table_name='pulse_nc')
    op.drop_index(op.f('ix_pulse_nc_status'), table_name='pulse_nc')
    op.drop_index(op.f('ix_pulse_nc_pulse_id'), table_name='pulse_nc')
    op.drop_index(op.f('ix_pulse_nc_project_name'), table_name='pulse_nc')
    op.drop_index(op.f('ix_pulse_nc_project_id'), table_name='pulse_nc')
    op.drop_index(op.f('ix_pulse_nc_package_name'), table_name='pulse_nc')
    op.drop_index(op.f('ix_pulse_nc_nc_label'), table_name='pulse_nc')
    op.drop_index(op.f('ix_pulse_nc_id'), table_name='pulse_nc')
    op.drop_index(op.f('ix_pulse_nc_current_handler'), table_name='pulse_nc')
    op.drop_index(op.f('ix_pulse_nc_cluster_name'), table_name='pulse_nc')
    op.drop_index(op.f('ix_pulse_nc_category'), table_name='pulse_nc')
    op.drop_table('pulse_nc')
    # ### end Alembic commands ###
